using System.Xml;

namespace AssetProcessor;

public static class GeneratedXmlFootprint
{
    private const string Prefix = " Generated by Asset Splitter.";
    private const int FileRetryCount = 8;

    public static void Save(XmlDocument document, string outputPath, PipelineContext context)
    {
        Apply(document, context);
        SaveWithRetry(document, outputPath);
    }

    public static void Apply(XmlDocument document, PipelineContext context)
    {
        if (document.DocumentElement is null)
        {
            return;
        }

        RemoveExistingFootprint(document);

        string commentText = BuildCommentText(context);
        if (string.IsNullOrWhiteSpace(commentText))
        {
            return;
        }

        XmlComment comment = document.CreateComment(commentText);
        document.InsertBefore(comment, document.DocumentElement);
        document.InsertAfter(document.CreateWhitespace(Environment.NewLine), comment);
    }

    public static string BuildCommentText(PipelineContext context)
    {
        if (context.DetectedGameBuild is null)
        {
            return "";
        }

        string gameName = GameTypeDetector.IsAnno117(context.DetectedGameType)
            ? "Anno 117 - Pax Romana"
            : "Anno 1800";
        string build = SanitizeCommentText(context.DetectedGameBuild.ToDisplayString());
        string builtAt = SanitizeCommentText(context.DetectedGameBuild.BuildTime);
        DateTimeOffset generatedAt = DateTimeOffset.Now;
        string timeZoneName = GetCurrentLocalTimeZoneName(generatedAt);

        string buildTimePart = string.IsNullOrWhiteSpace(builtAt) ? "" : $"; Build time: {builtAt}";
        return $"{Prefix} Game: {gameName}; Game build: {build}{buildTimePart}; Generated local time: {generatedAt:yyyy-MM-dd HH:mm:ss zzz} ({timeZoneName}) ";
    }

    public static string BuildGameBuildDescription(PipelineContext context)
    {
        if (context.DetectedGameBuild is null)
        {
            return "";
        }

        return context.DetectedGameBuild.ToDisplayString().Trim();
    }

    public static string BuildGameBuildTimeDescription(PipelineContext context)
    {
        return context.DetectedGameBuild?.BuildTime.Trim() ?? "";
    }

    public static string FormatGeneratedLocalTime(DateTimeOffset generatedAt)
    {
        string timeZoneName = GetCurrentLocalTimeZoneName(generatedAt);
        return $"{generatedAt:yyyy-MM-dd HH:mm:ss zzz} ({timeZoneName})";
    }

    private static void RemoveExistingFootprint(XmlDocument document)
    {
        XmlNode? node = document.FirstChild;
        while (node is not null && node != document.DocumentElement)
        {
            XmlNode? next = node.NextSibling;
            if (node.NodeType == XmlNodeType.Comment
                && node.Value?.Contains(Prefix.Trim(), StringComparison.OrdinalIgnoreCase) == true)
            {
                document.RemoveChild(node);
            }

            node = next;
        }
    }

    private static string SanitizeCommentText(string value) =>
        value.Replace("--", "-", StringComparison.Ordinal).Trim();

    private static void SaveWithRetry(XmlDocument document, string outputPath)
    {
        for (int attempt = 1; ; attempt++)
        {
            try
            {
                document.Save(outputPath);
                return;
            }
            catch (Exception ex) when (IsTransientFileAccess(ex) && attempt < FileRetryCount)
            {
                Thread.Sleep(GetRetryDelay(attempt));
            }
        }
    }

    private static bool IsTransientFileAccess(Exception ex) =>
        ex is IOException or UnauthorizedAccessException;

    private static int GetRetryDelay(int attempt) =>
        Math.Min(1000, 50 * (1 << Math.Min(attempt - 1, 5)));

    public static string GetCurrentLocalTimeZoneName(DateTimeOffset localTime)
    {
        TimeZoneInfo localZone = TimeZoneInfo.Local;
        bool daylight = localZone.IsDaylightSavingTime(localTime.DateTime);
        string name = daylight ? localZone.DaylightName : localZone.StandardName;
        return SanitizeCommentText(string.IsNullOrWhiteSpace(name) ? localZone.DisplayName : name);
    }
}
