using AssetProcessor;

namespace AssetProcessor;

/// <summary>
/// Loads template and fixlist config from the <c>config</c> folder
/// (<c>01_Templates</c>, <c>02_Processing_Rules</c>).
/// Resolves paths for both production (exe directory) and development (repo config folder).
/// </summary>
public static class TemplateLoader
{
    private const string TemplatesFolder = "01_Templates";
    private const string ProcessingRulesFolder = "02_Processing_Rules";
    private const string AutoGeneratedHeader = "# Auto-generated template list";

    /// <summary>
    /// Resolves a config file path by trying the production directory first, then two development layouts.
    /// </summary>
    /// <param name="subfolder">Config sub-folder (e.g. "01_Templates") or empty for config root.</param>
    /// <param name="filename">Config file name (e.g. "Anno1800_Templates.txt").</param>
    /// <returns>Full path to the file if found; otherwise the production path (for error messages).</returns>
    private static string GetConfigFilePath(string root, string subfolder, string filename)
    {
        return string.IsNullOrEmpty(subfolder)
          ? Path.Combine(root, "config", filename)
          : Path.Combine(root, "config", subfolder, filename);
    }

    public static string ResolveConfigPath(string subfolder, string filename)
    {
        return ConfigPathResolver.Resolve(subfolder, filename);
    }

    /// <summary>Returns the resolved path to the template list file for the given game.</summary>
    /// <param name="gameType">"anno1800" or "anno117".</param>
    public static string GetTemplateConfigPath(string gameType)
    {
        return ResolveConfigPath(TemplatesFolder, $"{GetGameConfigName(gameType)}_Templates.txt");
    }

    /// <summary>
    /// Returns <see langword="true"/> when the template list was auto-generated
    /// (first non-blank line starts with <c># Auto-generated</c>), is missing, or is unreadable.
    /// </summary>
    public static bool IsAutoGeneratedTemplateList(string filePath)
    {
        if (string.IsNullOrEmpty(filePath) || !File.Exists(filePath))
        {
            return true;
        }

        try
        {
            foreach (string line in File.ReadLines(filePath).Take(5))
            {
                string trimmed = line.Trim();
                if (trimmed.Length == 0)
                {
                    continue;
                }

                return trimmed.StartsWith(AutoGeneratedHeader, StringComparison.OrdinalIgnoreCase);
            }
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or ArgumentException or NotSupportedException)
        {
            System.Diagnostics.Debug.WriteLine($"[TemplateLoader] IsAutoGeneratedTemplateList({filePath}): {ex.Message}");
            // Non-fatal — treat as auto-generated to be safe
            return true;
        }

        return false;
    }

    /// <summary>Loads template names from config or a custom override path.</summary>
    /// <param name="gameType">"anno1800" or "anno117".</param>
    /// <param name="customTemplatePath">Optional path that takes precedence when the file exists.</param>
    /// <exception cref="FileNotFoundException">Thrown when no template config file can be located.</exception>
    public static string[] LoadTemplates(string gameType, string? customTemplatePath = null)
    {
        if (!string.IsNullOrEmpty(customTemplatePath) && File.Exists(customTemplatePath))
        {
            return LoadFromFile(customTemplatePath, $"custom template file: {customTemplatePath}");
        }

        string path = GetTemplateConfigPath(gameType);
        if (File.Exists(path))
        {
            return LoadFromFile(path, $"game config: {path}");
        }

        throw new FileNotFoundException(
          $"Template config file not found: {path}. Please run with --update-templates to populate from game.");
    }

    /// <summary>Loads fixlist template names (templates that receive full property merging) from config or a custom override.</summary>
    /// <param name="gameType">"anno1800" or "anno117".</param>
    /// <param name="customFixlistPath">Optional path that takes precedence when the file exists.</param>
    /// <exception cref="FileNotFoundException">Thrown when no fixlist config file can be located.</exception>
    public static string[] LoadFixlist(string gameType, string? customFixlistPath = null)
    {
        if (!string.IsNullOrEmpty(customFixlistPath) && File.Exists(customFixlistPath))
        {
            return LoadFromFile(customFixlistPath, $"custom fixlist file: {customFixlistPath}");
        }

        string gameName = GetGameConfigName(gameType);
        string path = ResolveConfigPath(ProcessingRulesFolder, $"{gameName}_Fixlist.txt");
        if (File.Exists(path))
        {
            return LoadFromFile(path, $"game config: {path}");
        }

        throw new FileNotFoundException(
          $"Fixlist config file not found: {path}. Please ensure config/02_Processing_Rules/{gameName}_Fixlist.txt exists.");
    }

    /// <summary>Reads non-blank, non-comment lines from a template file. Returns empty array on I/O error.</summary>
    private static string[] LoadFromFile(string filePath, string source)
    {
        try
        {
            string[] templates = [.. ReadConfigLines(filePath)];

            if (templates.Length == 0)
            {
                Console.WriteLine(string.Format(ConsoleMessages.Get("templateFileEmpty"), filePath));
                Console.WriteLine(ConsoleMessages.Get("noAssetsExtractedUpdateTemplates"));
            }

            return templates;
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or ArgumentException or NotSupportedException)
        {
            Console.WriteLine(string.Format(ConsoleMessages.Get("failedToLoadTemplatesFrom"), source, ex.Message));
            return [];
        }
    }

    private static IEnumerable<string> ReadConfigLines(string filePath)
    {
        return File.ReadAllLines(filePath)
          .Select(line => line.Trim())
          .Where(line => !string.IsNullOrWhiteSpace(line) && !line.StartsWith('#'));
    }

    private static string GetGameConfigName(string gameType)
    {
        return gameType.Equals("anno117", StringComparison.OrdinalIgnoreCase) ? "Anno117" : "Anno1800";
    }
}
