namespace AssetProcessor;

public static class TemplateBootstrapService
{
    public static string[] BootstrapTemplates(PipelineContext context, string gameType, string customTemplateFile, bool autoTemplates)
    {
        if (context.DebugMode)
            context.Log.Write("TEMPLATES", ConsoleMessages.Get("templatesCheckingUpdate"));

        try
        {
            if (File.Exists(Path.Combine(context.SourceXmlFolder, "templates.xml")))
            {
                if (TemplateExtractor.NeedsUpdate(context.SourceXmlFolder, gameType))
                {
                    string templateConfigPath = TemplateLoader.GetTemplateConfigPath(gameType);
                    bool allowAutoUpdate = TemplateLoader.IsAutoGeneratedTemplateList(templateConfigPath);
                    if (allowAutoUpdate)
                    {
                        context.Log.Write("INFO", ConsoleMessages.Get("autoUpdateUpdating"), always: true);
                        int count = TemplateExtractor.ExtractAndUpdateTemplates(context.SourceXmlFolder, gameType);
                        if (count > 0)
                            context.Log.Write("OK", string.Format(ConsoleMessages.Get("autoUpdateListUpdated"), count), always: true);
                        else
                            context.Log.Write("WARNING", ConsoleMessages.Get("autoUpdateReturnedZero"), always: true);
                    }
                    else
                    {
                        context.Log.Write("WARNING", ConsoleMessages.Get("autoUpdateSkipped"), always: true);
                    }
                }
                else if (context.DebugMode)
                {
                    context.Log.Write("OK", ConsoleMessages.Get("templatesAlreadyUpToDate"));
                }
            }
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or System.Xml.XmlException)
        {
            context.Log.Write("WARNING", string.Format(ConsoleMessages.Get("autoUpdateFailed"), ex.Message), always: true);
            context.Log.Write("INFO", ConsoleMessages.Get("continuingExistingTemplateConfig"), always: true);
        }

        try
        {
            string[] templateList;
            if (autoTemplates)
            {
                context.Log.Write("INFO", ConsoleMessages.Get("autoTemplatesExtractingAll"), always: true);
                HashSet<string> allTemplates = TemplateExtractor.ExtractTemplatesFromXml(TemplateExtractor.FindTemplatesXml(context.AssetRoot));
                if (allTemplates.Count > 0)
                {
                    templateList = [.. allTemplates.OrderBy(t => t)];
                    context.Log.Write("OK", string.Format(ConsoleMessages.Get("autoTemplatesFound"), templateList.Length), always: true);
                }
                else
                {
                    context.Log.Write("WARNING", ConsoleMessages.Get("autoTemplatesNoneFound"), always: true);
                    templateList = TemplateLoader.LoadTemplates(gameType, customTemplateFile);
                }
            }
            else
            {
                templateList = TemplateLoader.LoadTemplates(gameType, customTemplateFile);
            }

            if (context.DebugMode)
            {
                context.Log.Write("OK", string.Format(ConsoleMessages.Get("configReadyWithTemplates"), templateList.Length));
                context.Log.Debug(string.Format(ConsoleMessages.Get("debugTemplateListPath"), TemplateLoader.GetTemplateConfigPath(gameType)));
                context.Log.Debug(string.Format(ConsoleMessages.Get("debugTemplateFixlistCount"), TemplateLoader.LoadFixlist(gameType, customTemplateFile).Length));
            }

            return templateList;
        }
        catch (Exception ex)
        {
            context.Log.Write("ERROR", string.Format(ConsoleMessages.Get("failedToLoadTemplates"), ex.Message), always: true);
            throw new InvalidOperationException("Failed to load templates.", ex);
        }
    }
}
