import json
from pathlib import Path

base = Path(r'c:\Users\vadim\OneDrive\Documents\Asset Splitter UI\config\05_Console_Messages')

zh_trans = {
  'assetModsCreatedNote': '已创建资产模组文件夹。',
  'assetModsCreatedSingle': '[单 GUID MOD] 已在以下位置创建模组文件夹: {0}',
  'assetModsCreatedSummary': '[MODS] 已创建 {0} 个资产模组文件夹。已跳过 {1} 个。',
  'assetModsCreatingMany': '[MODS] 正在为每个资产在以下位置创建一个模组加载器文件夹: {0}',
  'assetModsCreatingSingle': '[单 GUID MOD] 正在 {0} 创建模组加载器模组',
  'assetModsOutputFolder': '[MODS] 输出文件夹: {0}',
  'assetModsProgress': '正在创建资产模组',
  'assetModsReadXmlWarning': "[WARN] 无法读取资产 XML '{0}': {1}",
  'assetModsSingleXmlOutput': '[单 GUID XML] 资产 XML 输出位置: {0}',
  'assetModsSkippingInvalidXml': '[WARN] 跳过无效 XML 的资产模组包: {0}',
  'assetNamesLoadedCount': '已加载 {0} 个资产名称。',
  'assetRegistryBuilding': '[ASSETS] 正在从游戏的主资产数据库构建资产注册表...',
  'assetRegistryCataloging': '[INFO] 正在对游戏中所有建筑、产品和物品进行分类',
  'assetRegistryComplete': '[完成] 资产注册表: 已分类并准备好 {0} 个游戏资产',
  'assetRegistryInherited': '[INFO] 已从父资产继承 {0} 个名称',
  'assetsXmlDocumentElementLoadFailed': '[错误] 无法加载 assets.xml 文档元素',
  'audioGeneratedLoadFailed': '[警告] 加载 audio_generated.xml 失败: {0}',
  'audioGeneratedMissing': '[INFO] 未找到 audio_generated.xml - 跳过音频资产名称',
  'audioRegistryComplete': '[完成] 音频注册表: 已分类 {0} 个音频资产',
  'autoTemplatesExtractingAll': '[自动模板] 正在从游戏文件中提取所有模板...',
  'autoTemplatesFound': '[自动模板] 在游戏中发现 {0} 个模板',
  'autoTemplatesNoneFound': '[警告] 自动提取未找到任何模板，将使用配置文件',
  'autoUpdateConfigUpdated': '[自动更新] \u2713 已用 {0} 个模板更新配置',
  'autoUpdateFailed': '[WARN] 自动更新模板失败: {0}',
  'autoUpdateListUpdated': '[自动更新] \u2713 已用游戏中的 {0} 个模板更新列表',
  'autoUpdateReturnedZero': '[WARN] 自动更新返回了 0 个模板，将使用现有配置',
  'autoUpdateSkipped': '[自动更新] 已跳过 - 模板列表似乎是自定义的。可使用 --update-templates 覆盖。',
  'autoUpdateUpdating': '[自动更新] 游戏模板已更改 - 正在更新配置...',
  'bannerAnno117': '\u2502  \U0001f3ae Anno 117 (Pax) ....... \u2713 已支持              \u2502',
  'bannerAnno1800': '\u2502  \U0001f3ae Anno 1800  ............ \u2713 已支持              \u2502',
  'bannerSubtitle': '\u2502  资产提取 & ModOp 生成器                          \u2502',
  'bannerTitle': '\u2502  ANNO ASSET SPLITTER v2.0 增强版                  \u2502',
  'clearedExistingOutputFolder': '[信息] 已清除现有输出文件夹',
  'compareTemplatesInConfig': '[比较] 配置中的模板: {0}',
  'compareTemplatesInGame': '[比较] 游戏中的模板:   {0}',
  'compareTemplatesMore': '[比较] ... 还有 {0} 个',
  'compareTemplatesNew': '  + {0}',
  'compareTemplatesNewHeader': '[比较] 新模板 ({0} 个):',
  'compareTemplatesRemoved': '  - {0}',
  'compareTemplatesRemovedHeader': '[比较] 已删除的模板 ({0} 个):',
  'compareTemplatesUnchanged': '[比较] 无变化 - 配置与游戏同步',
  'configReadyWithTemplates': '[CONFIG] 已准备好 {0} 个模板的处理配置',
  'configurationLoadedReady': '[CONFIG] 配置已加载，处理准备就绪',
  'continuingExistingTemplateConfig': '[CONFIG] 使用现有模板配置 - 运行 --update-templates 以更新',
  'convertingRawXmlToMods': '[转换中] 正在将原始 XML 资产转换为 ModOp 格式...',
  'couldNotCopyToSourceXml': '[警告] 无法将 {0} 复制到 source_xml: {1}',
  'couldNotMoveToTemplateFolder': '[警告] 无法将 {0} 移动到模板文件夹: {1}',
  'creatingOutputDirectory': '正在创建输出目录...',
  'dependenciesResolvedComplete': '[完成] \u2713 已解决 {0} 个依赖项',
  'dependencyResolutionComplete': '{0} 个资产的依赖关系解决完成 ({1})',
  'doneLabel': '[完成]',
  'extractAssetFailed': '[错误] 提取资产 {0} 失败: {1}',
  'extractConvertingAssets': '[提取] 正在将 {0} 个资产转换为 {1} 格式...',
  'extractCreatingXmlMods': '[INFO] 正在创建 Anno 可以加载和应用的 XML MOD 文件',
  'extractFormatModOp': '转换为可安装的 ModOp 格式',
  'extractFormatXml': '转换为 XML 格式（原始资产）',
  'extractedAssetsCount': '已提取 {0} 个资产。',
  'extractionCompleteHeader': '\n=== 提取完成 ===',
  'failedToLoadAssetNames': '无法加载资产名称: {0}',
  'failedToLoadTemplates': '[错误] 加载模板失败: {0}',
  'failedToLoadTemplatesFrom': '[错误] 从 {0} 加载模板失败: {1}',
  'failedToLoadXmlFile': '[错误] 加载 XML 文件失败: {0}',
  'filesFormattedCount': '已格式化 {0} 个文件。',
  'filesFound': '找到 {0} 个文件',
  'finalProcessingCompleted': '[完成] 最终处理完成:',
  'finalProcessingFiles': '正在对 {0} 个文件进行最终处理...',
  'fixLabel': '[修复]',
  'formatFeatureComments': '翻译注释 (-c)',
  'formatFeatureCommentsFolders': ', 注释 (-c), 文件夹 (-t)',
  'formatFeatureFlaggedOnly': '仅标记的后处理',
  'formatFeatureFolders': '模板文件夹 (-t)',
  'formatFeatureRegionalIngredients': ', 地区原料',
  'formatFeatureVectorCleanup': 'VectorElement 清理',
  'formatProcessingBaseAssetGuidFilesNoMove': '[格式化] 正在处理 {0} 个 BaseAssetGUID 参照文件（不移动文件夹）',
  'formatProcessingFiles': '[格式化] 正在处理 {0} 个文件 - {1}',
  'formatProcessingMainOutputFiles': '[格式化] 正在处理 {0} 个主输出文件',
  'formatSingleFileFailed': 'FormatSingleFile 在 {0} 失败: {1}',
  'formattingRunSummary': '[格式化] 格式化运行完成: 已处理 {0} 个文件 ({1})',
  'gameBuildDetected': '[游戏] 检测到 {0} 版本 {1}',
  'gameDirectoryNotFound': '[错误] 找不到 Anno 游戏目录: {0}',
  'guidIndexComplete': '[完成] GUID 文件索引: 已准备好 {0} 个 GUID-文件映射',
  'guidIndexNull': '[警告] GUID 索引为 null - 某些功能可能受影响',
  'inheritingTemplateProperties': '正在继承模板属性...',
  'issueDependencyChildLoadFailedHint': '请检查子文件是否为有效 XML 且未被其他进程锁定。',
  'issueDependencyChildLoadFailedMessage': "无法加载依赖子资产 '{0}': {1}",
  'issueDependencyChildLoadFailedRootCause': '在父属性合并之前，无法读取已准备的 BaseAssetGUID 子 XML 文件。',
  'issueTitle_DependencyChildLoadFailed': '依赖子项加载失败',
  'lineIdContextBuilding': '[TRANS] 正在从资产图构建 LineId 上下文索引...',
  'lineIdContextComplete': '[完成] LineId 上下文索引: 已准备好 {0} 个资产图标签',
  'lineIdContextLoadFailed': '[警告] 构建 LineId 上下文索引失败: {0}',
  'loadingGameTemplatesConfig': '[CONFIG] 正在加载游戏模板和处理配置...',
  'mergeAssetFailed': '[错误] 合并 {0} 失败: {1}',
  'mergeCheckingTemplateInheritance': '[合并] 正在检查 {0} 个资产的模板属性继承...',
  'mergeOnlyFixlistTemplates': '[INFO] 仅 fixlist 模板获得完整属性合并',
  'mergedTemplatesCount': '已为 {0} 个资产合并继承属性。',
  'mergingAssetProgress': '合并中: {0}',
  'mergingInheritedProperties': '[修复] 正在从父资产合并继承属性',
  'modExportBuildingPackages': '正在从 {0} 个已提取资产构建 MOD 文件夹...',
  'modExportRemovedStagingFolder': '[信息] 已删除中间 XML 文件夹: {0}',
  'modExportStagingFolderDeleteFailed': '[WARN] 无法删除中间 XML 文件夹 {0}: {1}',
  'noAssetsExtractedUpdateTemplates': '[INFO] 不会提取任何资产 - 使用 --update-templates 运行以从游戏中填充数据',
  'noTemplatesFound': '[错误] 在 templates.xml 中未找到模板',
  'outputDirectoryCreateFailed': "[错误] 创建输出目录 '{0}' 失败: {1}",
  'outputDirectoryCreated': '[OK] 输出目录创建成功',
  'outputFolderClearFailed': '[错误] 清除输出文件夹失败: {0}',
  'parentItemNull': '[WARN] 索引 {0} 处的父项为 null',
  'phase1Label': '=== 阶段 1: RDA 浏览器 ===',
  'phase2Label': '=== 阶段 2: 资产分割器 ===',
  'phase2bLabel': '=== 阶段 2B: 模板属性继承 ===',
  'phase3Label': '=== 阶段 3: 资产提取 ===',
  'phase3SplitTemplatesLabel': '=== 阶段 3B: 模板分割 ===',
  'phase4GuidIndexLabel': '=== 阶段 4: GUID 文件索引 ===',
  'phase5TemplateMergeLabel': '=== 阶段 5: 模板继承（合并）===',
  'phase6DependencyResolutionLabel': '=== 阶段 6: 依赖关系解决 ===',
  'phase7AssetModPackages': '=== 阶段 7: 资产 MOD 包 ===',
  'phase7FormattingLabel': '=== 阶段 7: 格式化 ===',
  'phase8AssetModPackages': '=== 阶段 8: 资产 MOD 包 ===',
  'phaseGuidIndex': '\n=== 阶段 2.5: 构建 GUID 索引 ===',
  'phaseRdaAnno117': '\n=== 阶段 1: 正在从 {0} 个 Anno 117 RDA 存档提取 ===',
  'phaseRdaAnno1800': '\n=== 阶段 1: 正在从 {0} 个 Anno 1800 RDA 存档提取 ===',
  'pipelineStarting': '正在启动资产提取管道...',
  'preparingBaseAssetGuid': '正在准备 BaseAssetGUID 参照传递...',
  'processedAssetsSummary': '已处理 {0} 个资产。',
  'processingAssetProgress': '处理中: {0}',
  'processingBaseAssetGuid': '正在处理 {0} 个 BaseAssetGUID 参照文件...',
  'propertyScanAnalyze': '[分析] 正在扫描 properties.xml 以识别可添加注释的 XML 元素...',
  'propertyScanComplete': '[完成] 属性分析: {0} 个 XML 元素可接受翻译注释',
  'propertyScanInfo': "[INFO] 正在查找值为 '0' 且可接受翻译 GUID 注释的属性",
  'rdaAnno117Detected': '[RDA] 检测到 Anno 117 - 正在解压 assets.xml, templates.xml, properties.xml, properties-meta.xml, datasets.xml, audio_generated.xml...',
  'rdaAnno1800Detected': '[RDA] 检测到 Anno 1800 - 正在解压 assets.xml, templates.xml, properties-toolone.xml, datasets.xml...',
  'rdaCompleteSelectLanguage': '[RDA 完成] 游戏文件已提取 - 请选择语言并重新运行以进行资产处理',
  'rdaDecompressionSuccessful': '[完成] RDA 解压成功 - 游戏数据现已可以 XML 形式访问',
  'rdaExtractingAnno117CoreFiles': '[INFO] 正在从 Anno 117 RDA 存档提取核心游戏定义文件',
  'rdaExtractingAnno1800CoreFiles': '[INFO] 正在从 Anno 1800 RDA 存档提取核心游戏定义文件',
  'rdaExtractionCompleteNonDebug': 'RDA 提取完成 \u2014 在 {2} 内处理了 {0}/{1} 个存档',
  'rdaExtractionCompleteShort': 'RDA 提取完成（在 {2} 内处理了 {0}/{1} 个存档）',
  'rdaExtractionFailed': '[错误] RDA 提取失败: {0}',
  'rdaExtractionSuccess': '[成功] 所有语言文件均已成功提取！',
  'rdaFilesContainAssets': 'RDA 文件是存储 Anno 游戏资产的容器存档（某些块/文件可能已压缩或加密）',
  'rdaLongRunningNote': '根据您的驱动器速度，这可能需要几分钟...\n',
  'readyToExtract': '\u2502  状态: 准备提取                                  \u2502',
  'regionAfrican': '非洲',
  'regionDefaultEuropean': '默认/欧洲',
  'regionalIngredientsApplied': '  * 地区原料: 已应用（Anno 1800 非洲 DLC）',
  'resolvingAssetProgress': '解决中: {0} <- {1}',
  'resolvingDependenciesSummary': '正在解决依赖关系',
  'scanningAssetProgress': '扫描中: {0}',
  'scanningDependenciesSummary': '正在扫描依赖关系',
  'singleGuidAsset': '[单 GUID] 资产: {0} - {1}',
  'singleGuidXmlOutput': '[单 GUID XML] 输出: {0}',
  'skippedNoCFlag': '已跳过（无 -c 标志）',
  'skippedNoTFlag': '已跳过（无 -t 标志）',
  'solutionRunLauncher': '  3. 通过启动器脚本运行以自动检测',
  'solutionUseFullPath': '  2. 使用 Anno 安装目录的完整路径',
  'solutionVerifyGamePath': '  1. 验证 Anno 游戏安装路径',
  'solutionsLabel': '解决方案:',
  'syntaxLabel': '语法:',
  'templateComparisonFailed': '[错误] 模板比较失败: {0}',
  'templateExtractionFailed': '[错误] 模板提取失败: {0}',
  'templateFileEmpty': '[WARN] 模板文件为空或仅包含注释: {0}',
  'templateInheritanceComplete': '[完成] 模板继承: {0}/{1} 个资产获得了完整属性',
  'templateNotFoundInCache': "[WARN] 缓存中未找到模板 '{0}' - 这不应该发生",
  'templateOrganizationSummary': '  * 模板整理: {0}',
  'templateParseFailed': '[错误] 解析 templates.xml 失败: {0}',
  'templateSplitMissingTemplatesXml': '[跳过] 未找到 templates.xml - 跳过模板分割',
  'templateSplitNoTemplateNodes': '[跳过] templates.xml 中没有 Template 节点',
  'templateUpdateFailed': '[错误] 更新模板失败',
  'templateUpdateSucceeded': '[OK] 已成功用 {0} 个模板更新模板列表',
  'templateWriteFailed': '[错误] 将模板写入文件失败: {0}',
  'templateXmlNotFound': '[错误] 找不到 templates.xml',
  'templateXmlNotFoundInPath': '[错误] 在 {0} 中找不到 templates.xml',
  'templatesAlreadyUpToDate': '[模板] 配置已与游戏保持最新',
  'templatesCheckingUpdate': '[模板] 正在检查模板配置是否需要更新...',
  'templatesInSync': '[OK] 模板已同步！\u2713',
  'textMetadataDictionaryComplete': '[完成] 文本元数据字典: 已准备好 {0} 个 LineId 开发者名称映射',
  'textMetadataLoadFailed': '[警告] 加载文本元数据失败: {0}',
  'textMetadataMappingsLoading': '[TRANS] 正在加载 LineId 开发者名称元数据 (texts_metadata.xml)...',
  'textMetadataMissing': '[警告] 未找到文本元数据文件: {0}（LineId 开发者名称不可用）',
  'totalTimeSummary': '总时间: {0}',
  'translationCommentsSummary': '  * 翻译注释: {0}',
  'translationDictionaryBuilding': '[INFO] 正在构建将数字 GUID 转换为可读名称的字典',
  'translationDictionaryComplete': '[完成] 翻译字典: 已准备好 {0} 个 GUID-名称映射',
  'translationFileLoadFailed': "[错误] 加载翻译文件 '{0}' 失败: {1}",
  'translationMappingsLoading': '[TRANS] 正在加载 GUID-文本翻译映射 ({0})...',
  'translationsLoadedCount': '已加载 {0} 条翻译。',
  'unexpectedFileProcessingError': '[错误] 处理文件时发生意外错误: {0}',
  'vectorCleanupApplied': '  * VectorElement 清理: 已应用于全部 {0} 个资产',
  'vectorCleanupSkippedSplitOnly': '  * VectorElement 清理: 已跳过（--no-default-properties / 仅分割）',
}

data = json.loads((base / 'console_zh.json').read_text(encoding='utf-8'))
for k, v in zh_trans.items():
    data[k] = v
(base / 'console_zh.json').write_text(
    json.dumps(dict(sorted(data.items())), ensure_ascii=False, indent=2) + '\n',
    encoding='utf-8'
)
print('zh done')
