import json
from pathlib import Path

base = Path(r'c:\Users\vadim\OneDrive\Documents\Asset Splitter UI\config\05_Console_Messages')

tw_trans = {
  'assetModsCreatedNote': '已建立資產模組資料夾。',
  'assetModsCreatedSingle': '[單一 GUID MOD] 模組資料夾已建立於: {0}',
  'assetModsCreatedSummary': '[MODS] 已建立 {0} 個資產模組資料夾。已跳過 {1} 個。',
  'assetModsCreatingMany': '[MODS] 正在 {0} 為每個資產建立一個模組載入器資料夾',
  'assetModsCreatingSingle': '[單一 GUID MOD] 正在 {0} 建立模組載入器模組',
  'assetModsOutputFolder': '[MODS] 輸出資料夾: {0}',
  'assetModsProgress': '正在建立資產模組',
  'assetModsReadXmlWarning': "[WARN] 無法讀取資產 XML '{0}': {1}",
  'assetModsSingleXmlOutput': '[單一 GUID XML] 資產 XML 輸出位置: {0}',
  'assetModsSkippingInvalidXml': '[WARN] 跳過無效 XML 的資產模組套件: {0}',
  'assetNamesLoadedCount': '已載入 {0} 個資產名稱。',
  'assetRegistryBuilding': '[ASSETS] 正在從遊戲的主要資產資料庫建立資產登錄...',
  'assetRegistryCataloging': '[INFO] 正在對遊戲中所有建築、產品和物品進行分類',
  'assetRegistryComplete': '[完成] 資產登錄: 已分類並準備好 {0} 個遊戲資產',
  'assetRegistryInherited': '[INFO] 已從父資產繼承 {0} 個名稱',
  'assetsXmlDocumentElementLoadFailed': '[錯誤] 無法載入 assets.xml 文件元素',
  'audioGeneratedLoadFailed': '[警告] 載入 audio_generated.xml 失敗: {0}',
  'audioGeneratedMissing': '[INFO] 找不到 audio_generated.xml - 跳過音訊資產名稱',
  'audioRegistryComplete': '[完成] 音訊登錄: 已分類 {0} 個音訊資產',
  'autoTemplatesExtractingAll': '[自動範本] 正在從遊戲檔案中提取所有範本...',
  'autoTemplatesFound': '[自動範本] 在遊戲中發現 {0} 個範本',
  'autoTemplatesNoneFound': '[警告] 自動提取未找到任何範本，將使用設定檔',
  'autoUpdateConfigUpdated': '[自動更新] \u2713 已用 {0} 個範本更新設定',
  'autoUpdateFailed': '[WARN] 自動更新範本失敗: {0}',
  'autoUpdateListUpdated': '[自動更新] \u2713 已用遊戲中的 {0} 個範本更新清單',
  'autoUpdateReturnedZero': '[WARN] 自動更新傳回了 0 個範本，將使用現有設定',
  'autoUpdateSkipped': '[自動更新] 已跳過 - 範本清單似乎是自訂的。可使用 --update-templates 覆寫。',
  'autoUpdateUpdating': '[自動更新] 遊戲範本已變更 - 正在更新設定...',
  'bannerAnno117': '\u2502  \U0001f3ae Anno 117 (Pax) ....... \u2713 已支援              \u2502',
  'bannerAnno1800': '\u2502  \U0001f3ae Anno 1800  ............ \u2713 已支援              \u2502',
  'bannerSubtitle': '\u2502  資產提取 & ModOp 產生器                          \u2502',
  'bannerTitle': '\u2502  ANNO ASSET SPLITTER v2.0 增強版                  \u2502',
  'clearedExistingOutputFolder': '[資訊] 已清除現有輸出資料夾',
  'compareTemplatesInConfig': '[比較] 設定中的範本: {0}',
  'compareTemplatesInGame': '[比較] 遊戲中的範本:   {0}',
  'compareTemplatesMore': '[比較] ... 還有 {0} 個',
  'compareTemplatesNew': '  + {0}',
  'compareTemplatesNewHeader': '[比較] 新範本 ({0} 個):',
  'compareTemplatesRemoved': '  - {0}',
  'compareTemplatesRemovedHeader': '[比較] 已移除的範本 ({0} 個):',
  'compareTemplatesUnchanged': '[比較] 無變化 - 設定與遊戲同步',
  'configReadyWithTemplates': '[CONFIG] 已準備好 {0} 個範本的處理設定',
  'configurationLoadedReady': '[CONFIG] 設定已載入，處理準備就緒',
  'continuingExistingTemplateConfig': '[CONFIG] 使用現有範本設定 - 執行 --update-templates 以更新',
  'convertingRawXmlToMods': '[轉換中] 正在將原始 XML 資產轉換為 ModOp 格式...',
  'couldNotCopyToSourceXml': '[警告] 無法將 {0} 複製到 source_xml: {1}',
  'couldNotMoveToTemplateFolder': '[警告] 無法將 {0} 移動到範本資料夾: {1}',
  'creatingOutputDirectory': '正在建立輸出目錄...',
  'dependenciesResolvedComplete': '[完成] \u2713 已解決 {0} 個相依項',
  'dependencyResolutionComplete': '{0} 個資產的相依關係解決完成 ({1})',
  'doneLabel': '[完成]',
  'extractAssetFailed': '[錯誤] 提取資產 {0} 失敗: {1}',
  'extractConvertingAssets': '[提取] 正在將 {0} 個資產轉換為 {1} 格式...',
  'extractCreatingXmlMods': '[INFO] 正在建立 Anno 可以載入並套用的 XML MOD 檔案',
  'extractFormatModOp': '轉換為可安裝的 ModOp 格式',
  'extractFormatXml': '轉換為 XML 格式（原始資產）',
  'extractedAssetsCount': '已提取 {0} 個資產。',
  'extractionCompleteHeader': '\n=== 提取完成 ===',
  'failedToLoadAssetNames': '無法載入資產名稱: {0}',
  'failedToLoadTemplates': '[錯誤] 載入範本失敗: {0}',
  'failedToLoadTemplatesFrom': '[錯誤] 從 {0} 載入範本失敗: {1}',
  'failedToLoadXmlFile': '[錯誤] 載入 XML 檔案失敗: {0}',
  'filesFormattedCount': '已格式化 {0} 個檔案。',
  'filesFound': '找到 {0} 個檔案',
  'finalProcessingCompleted': '[完成] 最終處理完成:',
  'finalProcessingFiles': '正在對 {0} 個檔案進行最終處理...',
  'fixLabel': '[修復]',
  'formatFeatureComments': '翻譯注釋 (-c)',
  'formatFeatureCommentsFolders': ', 注釋 (-c), 資料夾 (-t)',
  'formatFeatureFlaggedOnly': '僅標記的後處理',
  'formatFeatureFolders': '範本資料夾 (-t)',
  'formatFeatureRegionalIngredients': ', 地區原料',
  'formatFeatureVectorCleanup': 'VectorElement 清理',
  'formatProcessingBaseAssetGuidFilesNoMove': '[格式化] 正在處理 {0} 個 BaseAssetGUID 參照檔案（不移動資料夾）',
  'formatProcessingFiles': '[格式化] 正在處理 {0} 個檔案 - {1}',
  'formatProcessingMainOutputFiles': '[格式化] 正在處理 {0} 個主要輸出檔案',
  'formatSingleFileFailed': 'FormatSingleFile 在 {0} 失敗: {1}',
  'formattingRunSummary': '[格式化] 格式化執行完成: 已處理 {0} 個檔案 ({1})',
  'gameBuildDetected': '[遊戲] 偵測到 {0} 版本 {1}',
  'gameDirectoryNotFound': '[錯誤] 找不到 Anno 遊戲目錄: {0}',
  'guidIndexComplete': '[完成] GUID 檔案索引: 已準備好 {0} 個 GUID-檔案對應',
  'guidIndexNull': '[警告] GUID 索引為 null - 某些功能可能受影響',
  'inheritingTemplateProperties': '正在繼承範本屬性...',
  'issueDependencyChildLoadFailedHint': '請檢查子檔案是否為有效的 XML 且未被其他程序鎖定。',
  'issueDependencyChildLoadFailedMessage': "無法載入相依子資產 '{0}': {1}",
  'issueDependencyChildLoadFailedRootCause': '在父屬性合併之前，無法讀取已準備的 BaseAssetGUID 子 XML 檔案。',
  'issueTitle_DependencyChildLoadFailed': '相依性子項載入失敗',
  'lineIdContextBuilding': '[TRANS] 正在從資產圖建立 LineId 內容索引...',
  'lineIdContextComplete': '[完成] LineId 內容索引: 已準備好 {0} 個資產圖標籤',
  'lineIdContextLoadFailed': '[警告] 建立 LineId 內容索引失敗: {0}',
  'loadingGameTemplatesConfig': '[CONFIG] 正在載入遊戲範本和處理設定...',
  'mergeAssetFailed': '[錯誤] 合併 {0} 失敗: {1}',
  'mergeCheckingTemplateInheritance': '[合併] 正在檢查 {0} 個資產的範本屬性繼承...',
  'mergeOnlyFixlistTemplates': '[INFO] 僅 fixlist 範本獲得完整屬性合併',
  'mergedTemplatesCount': '已為 {0} 個資產合併繼承屬性。',
  'mergingAssetProgress': '合併中: {0}',
  'mergingInheritedProperties': '[修復] 正在從父資產合併繼承屬性',
  'modExportBuildingPackages': '正在從 {0} 個已提取資產建構 MOD 資料夾...',
  'modExportRemovedStagingFolder': '[資訊] 已刪除中間 XML 資料夾: {0}',
  'modExportStagingFolderDeleteFailed': '[WARN] 無法刪除中間 XML 資料夾 {0}: {1}',
  'noAssetsExtractedUpdateTemplates': '[INFO] 不會提取任何資產 - 使用 --update-templates 執行以從遊戲中填充資料',
  'noTemplatesFound': '[錯誤] 在 templates.xml 中未找到範本',
  'outputDirectoryCreateFailed': "[錯誤] 建立輸出目錄 '{0}' 失敗: {1}",
  'outputDirectoryCreated': '[OK] 輸出目錄建立成功',
  'outputFolderClearFailed': '[錯誤] 清除輸出資料夾失敗: {0}',
  'parentItemNull': '[WARN] 索引 {0} 處的父項為 null',
  'phase1Label': '=== 階段 1: RDA 瀏覽器 ===',
  'phase2Label': '=== 階段 2: 資產分割器 ===',
  'phase2bLabel': '=== 階段 2B: 範本屬性繼承 ===',
  'phase3Label': '=== 階段 3: 資產提取 ===',
  'phase3SplitTemplatesLabel': '=== 階段 3B: 範本分割 ===',
  'phase4GuidIndexLabel': '=== 階段 4: GUID 檔案索引 ===',
  'phase5TemplateMergeLabel': '=== 階段 5: 範本繼承（合併）===',
  'phase6DependencyResolutionLabel': '=== 階段 6: 相依關係解決 ===',
  'phase7AssetModPackages': '=== 階段 7: 資產 MOD 套件 ===',
  'phase7FormattingLabel': '=== 階段 7: 格式化 ===',
  'phase8AssetModPackages': '=== 階段 8: 資產 MOD 套件 ===',
  'phaseGuidIndex': '\n=== 階段 2.5: 建立 GUID 索引 ===',
  'phaseRdaAnno117': '\n=== 階段 1: 正在從 {0} 個 Anno 117 RDA 封存檔提取 ===',
  'phaseRdaAnno1800': '\n=== 階段 1: 正在從 {0} 個 Anno 1800 RDA 封存檔提取 ===',
  'pipelineStarting': '正在啟動資產提取管線...',
  'preparingBaseAssetGuid': '正在準備 BaseAssetGUID 參照傳遞...',
  'processedAssetsSummary': '已處理 {0} 個資產。',
  'processingAssetProgress': '處理中: {0}',
  'processingBaseAssetGuid': '正在處理 {0} 個 BaseAssetGUID 參照檔案...',
  'propertyScanAnalyze': '[分析] 正在掃描 properties.xml 以識別可新增注釋的 XML 元素...',
  'propertyScanComplete': '[完成] 屬性分析: {0} 個 XML 元素可接受翻譯注釋',
  'propertyScanInfo': "[INFO] 正在尋找值為 '0' 且可接受翻譯 GUID 注釋的屬性",
  'rdaAnno117Detected': '[RDA] 偵測到 Anno 117 - 正在解壓縮 assets.xml, templates.xml, properties.xml, properties-meta.xml, datasets.xml, audio_generated.xml...',
  'rdaAnno1800Detected': '[RDA] 偵測到 Anno 1800 - 正在解壓縮 assets.xml, templates.xml, properties-toolone.xml, datasets.xml...',
  'rdaCompleteSelectLanguage': '[RDA 完成] 遊戲檔案已提取 - 請選擇語言並重新執行以進行資產處理',
  'rdaDecompressionSuccessful': '[完成] RDA 解壓縮成功 - 遊戲資料現已可以 XML 形式存取',
  'rdaExtractingAnno117CoreFiles': '[INFO] 正在從 Anno 117 RDA 封存檔提取核心遊戲定義檔案',
  'rdaExtractingAnno1800CoreFiles': '[INFO] 正在從 Anno 1800 RDA 封存檔提取核心遊戲定義檔案',
  'rdaExtractionCompleteNonDebug': 'RDA 提取完成 \u2014 在 {2} 內處理了 {0}/{1} 個封存檔',
  'rdaExtractionCompleteShort': 'RDA 提取完成（在 {2} 內處理了 {0}/{1} 個封存檔）',
  'rdaExtractionFailed': '[錯誤] RDA 提取失敗: {0}',
  'rdaExtractionSuccess': '[成功] 所有語言檔案均已成功提取！',
  'rdaFilesContainAssets': 'RDA 檔案是儲存 Anno 遊戲資產的容器封存檔（某些區塊/檔案可能已壓縮或加密）',
  'rdaLongRunningNote': '根據您的磁碟機速度，這可能需要幾分鐘...\n',
  'readyToExtract': '\u2502  狀態: 準備提取                                  \u2502',
  'regionAfrican': '非洲',
  'regionDefaultEuropean': '預設/歐洲',
  'regionalIngredientsApplied': '  * 地區原料: 已套用（Anno 1800 非洲 DLC）',
  'resolvingAssetProgress': '解決中: {0} <- {1}',
  'resolvingDependenciesSummary': '正在解決相依關係',
  'scanningAssetProgress': '掃描中: {0}',
  'scanningDependenciesSummary': '正在掃描相依關係',
  'singleGuidAsset': '[單一 GUID] 資產: {0} - {1}',
  'singleGuidXmlOutput': '[單一 GUID XML] 輸出: {0}',
  'skippedNoCFlag': '已跳過（無 -c 旗標）',
  'skippedNoTFlag': '已跳過（無 -t 旗標）',
  'solutionRunLauncher': '  3. 透過啟動器指令碼執行以自動偵測',
  'solutionUseFullPath': '  2. 使用 Anno 安裝目錄的完整路徑',
  'solutionVerifyGamePath': '  1. 驗證 Anno 遊戲安裝路徑',
  'solutionsLabel': '解決方案:',
  'syntaxLabel': '語法:',
  'templateComparisonFailed': '[錯誤] 範本比較失敗: {0}',
  'templateExtractionFailed': '[錯誤] 範本提取失敗: {0}',
  'templateFileEmpty': '[WARN] 範本檔案為空或僅包含注釋: {0}',
  'templateInheritanceComplete': '[完成] 範本繼承: {0}/{1} 個資產獲得了完整屬性',
  'templateNotFoundInCache': "[WARN] 快取中未找到範本 '{0}' - 這不應該發生",
  'templateOrganizationSummary': '  * 範本整理: {0}',
  'templateParseFailed': '[錯誤] 解析 templates.xml 失敗: {0}',
  'templateSplitMissingTemplatesXml': '[跳過] 找不到 templates.xml - 跳過範本分割',
  'templateSplitNoTemplateNodes': '[跳過] templates.xml 中沒有 Template 節點',
  'templateUpdateFailed': '[錯誤] 更新範本失敗',
  'templateUpdateSucceeded': '[OK] 已成功用 {0} 個範本更新範本清單',
  'templateWriteFailed': '[錯誤] 將範本寫入檔案失敗: {0}',
  'templateXmlNotFound': '[錯誤] 找不到 templates.xml',
  'templateXmlNotFoundInPath': '[錯誤] 在 {0} 中找不到 templates.xml',
  'templatesAlreadyUpToDate': '[範本] 設定已與遊戲保持最新',
  'templatesCheckingUpdate': '[範本] 正在檢查範本設定是否需要更新...',
  'templatesInSync': '[OK] 範本已同步！\u2713',
  'textMetadataDictionaryComplete': '[完成] 文字中繼資料字典: 已準備好 {0} 個 LineId 開發者名稱對應',
  'textMetadataLoadFailed': '[警告] 載入文字中繼資料失敗: {0}',
  'textMetadataMappingsLoading': '[TRANS] 正在載入 LineId 開發者名稱中繼資料 (texts_metadata.xml)...',
  'textMetadataMissing': '[警告] 找不到文字中繼資料檔案: {0}（LineId 開發者名稱不可用）',
  'totalTimeSummary': '總時間: {0}',
  'translationCommentsSummary': '  * 翻譯注釋: {0}',
  'translationDictionaryBuilding': '[INFO] 正在建立將數字 GUID 轉換為可讀名稱的字典',
  'translationDictionaryComplete': '[完成] 翻譯字典: 已準備好 {0} 個 GUID-名稱對應',
  'translationFileLoadFailed': "[錯誤] 載入翻譯檔案 '{0}' 失敗: {1}",
  'translationMappingsLoading': '[TRANS] 正在載入 GUID-文字翻譯對應 ({0})...',
  'translationsLoadedCount': '已載入 {0} 條翻譯。',
  'unexpectedFileProcessingError': '[錯誤] 處理檔案時發生意外錯誤: {0}',
  'vectorCleanupApplied': '  * VectorElement 清理: 已套用於全部 {0} 個資產',
  'vectorCleanupSkippedSplitOnly': '  * VectorElement 清理: 已跳過（--no-default-properties / 僅分割）',
}

data = json.loads((base / 'console_tw.json').read_text(encoding='utf-8'))
for k, v in tw_trans.items():
    data[k] = v
(base / 'console_tw.json').write_text(
    json.dumps(dict(sorted(data.items())), ensure_ascii=False, indent=2) + '\n',
    encoding='utf-8'
)
print('tw done')
