import json
from pathlib import Path

base = Path(r'c:\Users\vadim\OneDrive\Documents\Asset Splitter UI\config\05_Console_Messages')

ko_trans = {
  'assetModsCreatedNote': '에셋 모드 폴더가 생성되었습니다.',
  'assetModsCreatedSingle': '[단일 GUID MOD] 모드 폴더 생성 위치: {0}',
  'assetModsCreatedSummary': '[MODS] {0}개의 에셋 모드 폴더를 생성했습니다. {1}개 건너뜀.',
  'assetModsCreatingMany': '[MODS] {0}에 에셋당 하나의 모드 로더 폴더를 생성 중',
  'assetModsCreatingSingle': '[단일 GUID MOD] {0}에 모드 로더 모드 생성 중',
  'assetModsOutputFolder': '[MODS] 출력 폴더: {0}',
  'assetModsProgress': '에셋 모드 생성 중',
  'assetModsReadXmlWarning': "[WARN] 에셋 XML을 읽을 수 없습니다 '{0}': {1}",
  'assetModsSingleXmlOutput': '[단일 GUID XML] 에셋 XML 출력 위치: {0}',
  'assetModsSkippingInvalidXml': '[WARN] 잘못된 XML에 대한 에셋 모드 패키지를 건너뜁니다: {0}',
  'assetNamesLoadedCount': '{0}개의 에셋 이름을 불러왔습니다.',
  'assetRegistryBuilding': "[ASSETS] 게임의 마스터 에셋 데이터베이스에서 에셋 레지스트리를 구축 중...",
  'assetRegistryCataloging': '[INFO] 게임 내 모든 건물, 제품, 아이템을 카탈로그화 중',
  'assetRegistryComplete': '[완료] 에셋 레지스트리: {0}개의 게임 에셋을 카탈로그화하고 준비 완료',
  'assetRegistryInherited': '[INFO] 부모 에셋에서 {0}개의 이름을 상속했습니다',
  'assetsXmlDocumentElementLoadFailed': '[오류] assets.xml 문서 요소를 불러올 수 없습니다',
  'audioGeneratedLoadFailed': '[경고] audio_generated.xml 불러오기 실패: {0}',
  'audioGeneratedMissing': '[INFO] audio_generated.xml을 찾을 수 없습니다 - 오디오 에셋 이름을 건너뜁니다',
  'audioRegistryComplete': '[완료] 오디오 레지스트리: {0}개의 오디오 에셋을 카탈로그화',
  'autoTemplatesExtractingAll': '[자동 템플릿] 게임 파일에서 모든 템플릿을 추출 중...',
  'autoTemplatesFound': '[자동 템플릿] 게임에서 {0}개의 템플릿을 발견했습니다',
  'autoTemplatesNoneFound': '[경고] 자동 추출로 템플릿을 찾을 수 없습니다. 구성 파일을 사용합니다',
  'autoUpdateConfigUpdated': '[자동 업데이트] \u2713 {0}개의 템플릿으로 구성을 업데이트했습니다',
  'autoUpdateFailed': '[WARN] 템플릿 자동 업데이트 실패: {0}',
  'autoUpdateListUpdated': '[자동 업데이트] \u2713 게임에서 {0}개의 템플릿으로 목록을 업데이트했습니다',
  'autoUpdateReturnedZero': '[WARN] 자동 업데이트가 0개의 템플릿을 반환했습니다. 기존 구성을 사용합니다',
  'autoUpdateSkipped': '[자동 업데이트] 건너뜀 - 템플릿 목록이 커스텀인 것 같습니다. --update-templates로 덮어쓸 수 있습니다.',
  'autoUpdateUpdating': '[자동 업데이트] 게임 템플릿이 변경되었습니다 - 구성을 업데이트 중...',
  'bannerAnno117': '\u2502  \U0001f3ae Anno 117 (Pax) ....... \u2713 지원됨              \u2502',
  'bannerAnno1800': '\u2502  \U0001f3ae Anno 1800  ............ \u2713 지원됨              \u2502',
  'bannerSubtitle': '\u2502  에셋 추출 & ModOp 생성기                        \u2502',
  'bannerTitle': '\u2502  ANNO ASSET SPLITTER v2.0 향상판                  \u2502',
  'clearedExistingOutputFolder': '[정보] 기존 출력 폴더를 지웠습니다',
  'compareTemplatesInConfig': '[비교] 구성의 템플릿: {0}',
  'compareTemplatesInGame': '[비교] 게임의 템플릿:   {0}',
  'compareTemplatesMore': '[비교] ... 그 외 {0}개 더',
  'compareTemplatesNew': '  + {0}',
  'compareTemplatesNewHeader': '[비교] 새 템플릿 ({0}개):',
  'compareTemplatesRemoved': '  - {0}',
  'compareTemplatesRemovedHeader': '[비교] 제거된 템플릿 ({0}개):',
  'compareTemplatesUnchanged': '[비교] 변경 없음 - 구성이 게임과 동기화되어 있습니다',
  'configReadyWithTemplates': '[CONFIG] {0}개의 템플릿으로 처리 구성 준비 완료',
  'configurationLoadedReady': '[CONFIG] 구성이 로드되고 처리 준비가 완료되었습니다',
  'continuingExistingTemplateConfig': '[CONFIG] 기존 템플릿 구성을 사용합니다 - 업데이트하려면 --update-templates를 실행하세요',
  'convertingRawXmlToMods': '[변환 중] 원시 XML 에셋을 ModOp 형식으로 변환 중...',
  'couldNotCopyToSourceXml': '[경고] {0}을 source_xml로 복사할 수 없습니다: {1}',
  'couldNotMoveToTemplateFolder': '[경고] {0}을 템플릿 폴더로 이동할 수 없습니다: {1}',
  'creatingOutputDirectory': '출력 디렉토리 생성 중...',
  'dependenciesResolvedComplete': '[완료] \u2713 {0}개의 종속성을 해결했습니다',
  'dependencyResolutionComplete': '{0}개 에셋의 종속성 해결 완료 ({1})',
  'doneLabel': '[완료]',
  'extractAssetFailed': '[오류] 에셋 {0} 추출 실패: {1}',
  'extractConvertingAssets': '[추출] {0}개의 에셋을 {1} 형식으로 변환 중...',
  'extractCreatingXmlMods': '[INFO] Anno가 로드하고 적용할 수 있는 XML MOD 파일 생성 중',
  'extractFormatModOp': '설치 가능한 ModOp 형식으로',
  'extractFormatXml': 'XML 형식으로 (원시 에셋)',
  'extractedAssetsCount': '{0}개의 에셋을 추출했습니다.',
  'extractionCompleteHeader': '\n=== 추출 완료 ===',
  'failedToLoadAssetNames': '에셋 이름을 불러올 수 없습니다: {0}',
  'failedToLoadTemplates': '[오류] 템플릿 불러오기 실패: {0}',
  'failedToLoadTemplatesFrom': '[오류] {0}에서 템플릿 불러오기 실패: {1}',
  'failedToLoadXmlFile': '[오류] XML 파일 불러오기 실패: {0}',
  'filesFormattedCount': '{0}개의 파일을 포맷했습니다.',
  'filesFound': '{0}개의 파일을 찾았습니다',
  'finalProcessingCompleted': '[완료] 최종 처리 완료:',
  'finalProcessingFiles': '{0}개 파일의 최종 처리 중...',
  'fixLabel': '[수정]',
  'formatFeatureComments': '번역 주석 (-c)',
  'formatFeatureCommentsFolders': ', 주석 (-c), 폴더 (-t)',
  'formatFeatureFlaggedOnly': '플래그된 후처리만',
  'formatFeatureFolders': '템플릿 폴더 (-t)',
  'formatFeatureRegionalIngredients': ', 지역 재료',
  'formatFeatureVectorCleanup': 'VectorElement 정리',
  'formatProcessingBaseAssetGuidFilesNoMove': '[포맷] {0}개의 BaseAssetGUID 참조 파일 처리 중 (폴더 이동 없음)',
  'formatProcessingFiles': '[포맷] {0}개의 파일 처리 중 - {1}',
  'formatProcessingMainOutputFiles': '[포맷] {0}개의 주 출력 파일 처리 중',
  'formatSingleFileFailed': 'FormatSingleFile이 {0}에서 실패: {1}',
  'formattingRunSummary': '[포맷] 포맷 실행 완료: {0}개 파일 처리됨 ({1})',
  'gameBuildDetected': '[게임] {0} 빌드 {1} 감지됨',
  'gameDirectoryNotFound': '[오류] Anno 게임 디렉토리를 찾을 수 없습니다: {0}',
  'guidIndexComplete': '[완료] GUID 파일 인덱스: {0}개의 GUID-파일 매핑 준비 완료',
  'guidIndexNull': '[경고] GUID 인덱스가 null입니다 - 일부 기능이 영향을 받을 수 있습니다',
  'inheritingTemplateProperties': '템플릿 속성 상속 중...',
  'issueDependencyChildLoadFailedHint': '자식 파일이 유효한 XML인지, 다른 프로세스에 의해 잠기지 않았는지 확인하세요.',
  'issueDependencyChildLoadFailedMessage': "종속 자식 에셋 '{0}'을 불러올 수 없습니다: {1}",
  'issueDependencyChildLoadFailedRootCause': '부모 속성이 병합되기 전에 준비된 BaseAssetGUID 자식 XML 파일을 읽을 수 없습니다.',
  'issueTitle_DependencyChildLoadFailed': '종속성 자식 불러오기 실패',
  'lineIdContextBuilding': '[TRANS] 에셋 그래프에서 LineId 컨텍스트 인덱스를 구축 중...',
  'lineIdContextComplete': '[완료] LineId 컨텍스트 인덱스: {0}개의 에셋 그래프 레이블 준비 완료',
  'lineIdContextLoadFailed': '[경고] LineId 컨텍스트 인덱스 구축 실패: {0}',
  'loadingGameTemplatesConfig': '[CONFIG] 게임 템플릿 및 처리 구성을 로드 중...',
  'mergeAssetFailed': '[오류] {0} 병합 실패: {1}',
  'mergeCheckingTemplateInheritance': '[병합] {0}개의 에셋에서 템플릿 속성 상속을 확인 중...',
  'mergeOnlyFixlistTemplates': '[INFO] fixlist 템플릿만 완전한 속성을 병합합니다',
  'mergedTemplatesCount': '{0}개의 에셋에 대해 상속 속성을 병합했습니다.',
  'mergingAssetProgress': '병합 중: {0}',
  'mergingInheritedProperties': '[수정] 부모 에셋에서 상속 속성 병합 중',
  'modExportBuildingPackages': '{0}개의 추출된 에셋에서 MOD 폴더 구축 중...',
  'modExportRemovedStagingFolder': '[정보] 중간 XML 폴더를 삭제했습니다: {0}',
  'modExportStagingFolderDeleteFailed': '[WARN] 중간 XML 폴더 {0}를 삭제할 수 없습니다: {1}',
  'noAssetsExtractedUpdateTemplates': '[INFO] 추출할 에셋이 없습니다 - --update-templates로 실행하여 게임에서 데이터를 추가하세요',
  'noTemplatesFound': '[오류] templates.xml에 템플릿이 없습니다',
  'outputDirectoryCreateFailed': "[오류] 출력 디렉토리 '{0}' 생성 실패: {1}",
  'outputDirectoryCreated': '[OK] 출력 디렉토리가 성공적으로 생성되었습니다',
  'outputFolderClearFailed': '[오류] 출력 폴더 지우기 실패: {0}',
  'parentItemNull': '[WARN] 인덱스 {0}의 부모 항목이 null입니다',
  'phase1Label': '=== 단계 1: RDA 탐색기 ===',
  'phase2Label': '=== 단계 2: 에셋 분할기 ===',
  'phase2bLabel': '=== 단계 2B: 템플릿 속성 상속 ===',
  'phase3Label': '=== 단계 3: 에셋 추출 ===',
  'phase3SplitTemplatesLabel': '=== 단계 3B: 템플릿 분할 ===',
  'phase4GuidIndexLabel': '=== 단계 4: GUID 파일 인덱스 ===',
  'phase5TemplateMergeLabel': '=== 단계 5: 템플릿 상속 (병합) ===',
  'phase6DependencyResolutionLabel': '=== 단계 6: 종속성 해결 ===',
  'phase7AssetModPackages': '=== 단계 7: 에셋 MOD 패키지 ===',
  'phase7FormattingLabel': '=== 단계 7: 포맷 ===',
  'phase8AssetModPackages': '=== 단계 8: 에셋 MOD 패키지 ===',
  'phaseGuidIndex': '\n=== 단계 2.5: GUID 인덱스 구축 중 ===',
  'phaseRdaAnno117': '\n=== 단계 1: {0}개의 Anno 117 RDA 아카이브에서 추출 중 ===',
  'phaseRdaAnno1800': '\n=== 단계 1: {0}개의 Anno 1800 RDA 아카이브에서 추출 중 ===',
  'pipelineStarting': '에셋 추출 파이프라인을 시작 중...',
  'preparingBaseAssetGuid': 'BaseAssetGUID 참조 패스를 준비 중...',
  'processedAssetsSummary': '{0}개의 에셋을 처리했습니다.',
  'processingAssetProgress': '처리 중: {0}',
  'processingBaseAssetGuid': '{0}개의 BaseAssetGUID 참조 파일 처리 중...',
  'propertyScanAnalyze': "[분석] 주석 적용 가능한 XML 요소를 찾기 위해 properties.xml 스캔 중...",
  'propertyScanComplete': '[완료] 속성 분석: {0}개의 XML 요소가 번역 주석을 받을 수 있습니다',
  'propertyScanInfo': "[INFO] 번역된 GUID 주석을 받을 수 있는 값이 '0'인 속성 찾는 중",
  'rdaAnno117Detected': '[RDA] Anno 117 감지됨 - assets.xml, templates.xml, properties.xml, properties-meta.xml, datasets.xml, audio_generated.xml 압축 해제 중...',
  'rdaAnno1800Detected': '[RDA] Anno 1800 감지됨 - assets.xml, templates.xml, properties-toolone.xml, datasets.xml 압축 해제 중...',
  'rdaCompleteSelectLanguage': '[RDA 완료] 게임 파일 추출됨 - 언어를 선택하고 다시 실행하여 에셋 처리를 진행하세요',
  'rdaDecompressionSuccessful': '[완료] RDA 압축 해제 성공 - 게임 데이터가 XML로 접근 가능해졌습니다',
  'rdaExtractingAnno117CoreFiles': '[INFO] Anno 117 RDA 아카이브에서 핵심 게임 정의 파일 추출 중',
  'rdaExtractingAnno1800CoreFiles': '[INFO] Anno 1800 RDA 아카이브에서 핵심 게임 정의 파일 추출 중',
  'rdaExtractionCompleteNonDebug': 'RDA 추출 완료 \u2014 {2}에서 {0}/{1}개의 아카이브를 처리했습니다',
  'rdaExtractionCompleteShort': 'RDA 추출 완료 ({2}에서 {0}/{1}개의 아카이브 처리)',
  'rdaExtractionFailed': '[오류] RDA 추출 실패: {0}',
  'rdaExtractionSuccess': '[성공] 모든 언어 파일을 성공적으로 추출했습니다!',
  'rdaFilesContainAssets': 'RDA 파일은 Anno 게임 에셋을 저장하는 컨테이너 아카이브입니다 (일부 블록/파일은 압축되거나 암호화될 수 있습니다)',
  'rdaLongRunningNote': '드라이브 속도에 따라 몇 분이 걸릴 수 있습니다...\n',
  'readyToExtract': '\u2502  상태: 추출 준비 완료                            \u2502',
  'regionAfrican': '아프리카',
  'regionDefaultEuropean': '기본/유럽',
  'regionalIngredientsApplied': '  * 지역 재료: 적용됨 (Anno 1800 아프리카 DLC)',
  'resolvingAssetProgress': '해결 중: {0} <- {1}',
  'resolvingDependenciesSummary': '종속성 해결 중',
  'scanningAssetProgress': '스캔 중: {0}',
  'scanningDependenciesSummary': '종속성 스캔 중',
  'singleGuidAsset': '[단일 GUID] 에셋: {0} - {1}',
  'singleGuidXmlOutput': '[단일 GUID XML] 출력: {0}',
  'skippedNoCFlag': '건너뜀 (-c 플래그 없음)',
  'skippedNoTFlag': '건너뜀 (-t 플래그 없음)',
  'solutionRunLauncher': '  3. 자동 감지를 위해 런처 스크립트로 실행',
  'solutionUseFullPath': '  2. Anno 설치 디렉토리의 전체 경로 사용',
  'solutionVerifyGamePath': '  1. Anno 게임 설치 경로 확인',
  'solutionsLabel': '해결책:',
  'syntaxLabel': '구문:',
  'templateComparisonFailed': '[오류] 템플릿 비교 실패: {0}',
  'templateExtractionFailed': '[오류] 템플릿 추출 실패: {0}',
  'templateFileEmpty': '[WARN] 템플릿 파일이 비어있거나 주석만 있습니다: {0}',
  'templateInheritanceComplete': '[완료] 템플릿 상속: {0}/{1}개의 에셋이 완전한 속성을 얻었습니다',
  'templateNotFoundInCache': "[WARN] 캐시에서 템플릿 '{0}'을 찾을 수 없습니다 - 발생하면 안 됩니다",
  'templateOrganizationSummary': '  * 템플릿 정리: {0}',
  'templateParseFailed': '[오류] templates.xml 파싱 실패: {0}',
  'templateSplitMissingTemplatesXml': '[건너뜀] templates.xml을 찾을 수 없습니다 - 템플릿 분할을 건너뜁니다',
  'templateSplitNoTemplateNodes': '[건너뜀] templates.xml에 Template 노드가 없습니다',
  'templateUpdateFailed': '[오류] 템플릿 업데이트에 실패했습니다',
  'templateUpdateSucceeded': '[OK] {0}개의 템플릿으로 템플릿 목록을 성공적으로 업데이트했습니다',
  'templateWriteFailed': '[오류] 템플릿을 파일에 쓰기 실패: {0}',
  'templateXmlNotFound': '[오류] templates.xml을 찾을 수 없습니다',
  'templateXmlNotFoundInPath': '[오류] {0}에서 templates.xml을 찾을 수 없습니다',
  'templatesAlreadyUpToDate': '[템플릿] 구성이 이미 게임과 최신 상태입니다',
  'templatesCheckingUpdate': '[템플릿] 템플릿 구성 업데이트가 필요한지 확인 중...',
  'templatesInSync': '[OK] 템플릿이 동기화되었습니다! \u2713',
  'textMetadataDictionaryComplete': '[완료] 텍스트 메타데이터 사전: {0}개의 LineId 개발자 이름 매핑 준비 완료',
  'textMetadataLoadFailed': '[경고] 텍스트 메타데이터 불러오기 실패: {0}',
  'textMetadataMappingsLoading': '[TRANS] LineId 개발자 이름 메타데이터 로드 중 (texts_metadata.xml)...',
  'textMetadataMissing': '[경고] 텍스트 메타데이터 파일을 찾을 수 없습니다: {0} (LineId 개발자 이름 사용 불가)',
  'totalTimeSummary': '총 시간: {0}',
  'translationCommentsSummary': '  * 번역 주석: {0}',
  'translationDictionaryBuilding': '[INFO] 숫자 GUID를 읽기 쉬운 이름으로 변환하는 사전을 구축 중',
  'translationDictionaryComplete': '[완료] 번역 사전: {0}개의 GUID-이름 매핑 준비 완료',
  'translationFileLoadFailed': "[오류] 번역 파일 '{0}' 불러오기 실패: {1}",
  'translationMappingsLoading': '[TRANS] GUID-텍스트 번역 매핑 로드 중 ({0})...',
  'translationsLoadedCount': '{0}개의 번역을 불러왔습니다.',
  'unexpectedFileProcessingError': '[오류] 파일 처리 중 예기치 않은 오류가 발생했습니다: {0}',
  'vectorCleanupApplied': '  * VectorElement 정리: 전체 {0}개의 에셋에 적용됨',
  'vectorCleanupSkippedSplitOnly': '  * VectorElement 정리: 건너뜀 (--no-default-properties / 분할 전용)',
}

data = json.loads((base / 'console_ko.json').read_text(encoding='utf-8'))
for k, v in ko_trans.items():
    data[k] = v
(base / 'console_ko.json').write_text(
    json.dumps(dict(sorted(data.items())), ensure_ascii=False, indent=2) + '\n',
    encoding='utf-8'
)
print('ko done')
