import json, os

base = r'C:\Users\vadim\OneDrive\Documents\Asset Splitter UI\config\05_Console_Messages'
path = os.path.join(base, 'console_de.json')

with open(path, encoding='utf-8') as f:
    data = json.load(f)

tr = {
    # user-visible short strings
    "regionAfrican": "Afrika",
    "regionDefaultEuropean": "Standard/Europa",
    "regionalIngredientsApplied": "  * Regionale Zutaten: Angewendet (Anno 1800 Afrika-DLC)",
    "resolvingAssetProgress": "Aufloesen: {0} <- {1}",
    "scanningAssetProgress": "Scannen: {0}",
    "resolvingDependenciesSummary": "Abhaengigkeiten aufloesen",
    "scanningDependenciesSummary": "Abhaengigkeiten scannen",
    "readmeXPathExamples": "- Namen aendern: `Path=\"/Values/Standard/Name\"`\n- Produktivitaet aendern: `Path=\"/Values/FactoryUpgrade/ProductivityUpgrade/Value\"`\n- Neues Element unter Item hinzufuegen: `Path=\"/Values/Item\"` (mit Type=add)\n- Nach Standard einfuegen: `Path=\"/Values/Standard\"` (mit Type=addNextSibling)\n- Kostenknoten entfernen: `Path=\"/Values/Cost\"` (mit Type=remove)\n- Alle Assets auf einer Insel ansprechen: `Path=\"//Asset[Values/Building/Island='123']\"`",
    # pipeline / console strings
    "rdaExtractionSuccess": "[ERFOLG] Alle Sprachdateien erfolgreich extrahiert!",
    "modCategoryName": "Asset Splitter",
    "modDescriptionTemplate": "Generierter Asset-Mod fuer Template '{0}'.",
    "modDescriptionGameBuildSuffix": "Erstellt fuer Spielversion {0}.",
    "failedToLoadAssetNames": "Asset-Namen konnten nicht geladen werden: {0}.",
    "templateXmlNotFoundInPath": "[FEHLER] templates.xml nicht gefunden in {0}.",
    "templateXmlNotFound": "[FEHLER] templates.xml nicht gefunden.",
    "noTemplatesFound": "[FEHLER] Keine Templates in templates.xml gefunden.",
    "templateExtractionFailed": "[FEHLER] Template-Extraktion fehlgeschlagen: {0}",
    "templateParseFailed": "[FEHLER] Parsen von templates.xml fehlgeschlagen: {0}.",
    "templateComparisonFailed": "[FEHLER] Template-Vergleich fehlgeschlagen: {0}",
    "templateWriteFailed": "[FEHLER] Templates konnten nicht in Datei geschrieben werden: {0}",
    "templateUpdateSucceeded": "[OK] Template-Liste erfolgreich aktualisiert: {0} Templates.",
    "templateUpdateFailed": "[FEHLER] Template-Aktualisierung fehlgeschlagen.",
    "templateFileEmpty": "[WARN] Template-Datei leer oder enthaelt nur Kommentare: {0}",
    "noAssetsExtractedUpdateTemplates": "[INFO] Es werden keine Assets extrahiert - mit --update-templates ausfuehren, um aus dem Spiel zu befuellen.",
    "failedToLoadTemplatesFrom": "[FEHLER] Templates konnten nicht aus {0} geladen werden: {1}.",
    "failedToLoadTemplates": "[FEHLER] Templates konnten nicht geladen werden: {0}",
    "compareTemplatesInGame": "[VERGLEICH] Templates im Spiel: {0}",
    "compareTemplatesInConfig": "[VERGLEICH] Templates in Konfiguration: {0}",
    "compareTemplatesUnchanged": "[VERGLEICH] Unveraendert: {0}",
    "compareTemplatesNew": "[VERGLEICH] Neu im Spiel: {0}",
    "compareTemplatesRemoved": "[VERGLEICH] Aus Spiel entfernt: {0}",
    "compareTemplatesNewHeader": "[NEU] Templates im Spiel, aber nicht in Konfiguration:",
    "compareTemplatesRemovedHeader": "[ENTFERNT] Templates in Konfiguration, aber nicht im Spiel:",
    "compareTemplatesMore": "      ... und {0} weitere",
    "templatesInSync": "[OK] Templates sind synchron! \u2713",
    "preparingBaseAssetGuid": "BaseAssetGUID-Durchlauf wird vorbereitet...",
    "processingBaseAssetGuid": "{0} BaseAssetGUID-Referenzdateien werden verarbeitet...",
    "autoUpdateUpdating": "[AUTO-UPDATE] Spiel-Templates geaendert - Konfiguration wird aktualisiert...",
    "autoUpdateConfigUpdated": "[AUTO-UPDATE] \u2713 Template-Konfiguration aktualisiert: {0} Templates",
    "autoUpdateListUpdated": "[AUTO-UPDATE] \u2713 Template-Liste aktualisiert: {0} Templates aus Spiel",
    "autoUpdateSkipped": "[AUTO-UPDATE] Uebersprungen - Template-Liste scheint manuell geaendert zu sein. Verwende --update-templates zum Ueberschreiben.",
    "autoUpdateReturnedZero": "[WARN] Auto-Update der Templates lieferte 0 Templates, vorhandene Konfiguration wird verwendet",
    "templatesAlreadyUpToDate": "[TEMPLATES] Konfiguration entspricht bereits dem Spiel",
    "autoUpdateFailed": "[WARN] Auto-Update der Templates fehlgeschlagen: {0}",
    "continuingExistingTemplateConfig": "[INFO] Vorhandene Template-Konfiguration wird weiterverwendet",
    "autoTemplatesExtractingAll": "[AUTO-TEMPLATES] Alle Templates aus Spieldateien werden extrahiert...",
    "autoTemplatesFound": "[AUTO-TEMPLATES] Templates im Spiel gefunden: {0}",
    "autoTemplatesNoneFound": "[WARN] Auto-Extraktion der Templates hat nichts gefunden, Konfigurationsdatei wird verwendet",
    "configReadyWithTemplates": "[CONFIG] Bereit mit {0} Templates",
    "assetModsCreatingSingle": "[SINGLE GUID MOD] Mod Loader-Mod wird erstellt: {0}",
    "assetModsCreatingMany": "[MODS] Mod Loader-Ordner fuer jedes Asset werden erstellt: {0}",
    "assetModsProgress": "Asset-Mods werden erstellt",
    "assetModsCreatedSingle": "[SINGLE GUID MOD] Mod-Ordner erstellt: {0}",
    "assetModsSingleXmlOutput": "[SINGLE GUID XML] Asset-XML gespeichert: {0}",
    "assetModsCreatedSummary": "[MODS] Asset-Mod-Ordner erstellt: {0}. Uebersprungen: {1}.",
    "assetModsOutputFolder": "[MODS] Ausgabeordner: {0}",
    "assetModsSkippingInvalidXml": "[WARN] Asset-Mod-Paket wegen ungueltigem XML uebersprungen: {0}",
    "assetModsReadXmlWarning": "[WARN] Asset-XML '{0}' konnte nicht gelesen werden: {1}",
    "extractFormatModOp": "in installierbares ModOp-Format",
    "extractFormatXml": "in XML (reines Asset)",
    "extractConvertingAssets": "[EXTRACT] {0} Assets {1} werden konvertiert...",
    "extractCreatingXmlMods": "[INFO] XML-Mod-Dateien werden erstellt, die Anno laden und auf das Spiel anwenden kann",
    "extractAssetFailed": "[FEHLER] Asset {0} konnte nicht extrahiert werden: {1}",
    "assetRegistryBuilding": "[ASSETS] Asset-Registrierung wird aus der Spiel-Master-Datenbank aufgebaut...",
    "assetRegistryCataloging": "[INFO] Alle Gebaeude, Produkte und Gegenstaende im Spiel werden katalogisiert",
    "assetRegistryComplete": "[COMPLETE] Asset-Registrierung: {0} Spiel-Assets katalogisiert",
    "assetRegistryInherited": "[INFO] {0} Namen von uebergeordneten Assets geerbt",
    "audioGeneratedMissing": "[INFO] audio_generated.xml nicht gefunden - Audio-Asset-Namen werden uebersprungen",
    "audioRegistryComplete": "[COMPLETE] Audio-Registrierung: {0} Audio-Assets katalogisiert",
    "audioGeneratedLoadFailed": "[WARN] audio_generated.xml konnte nicht geladen werden: {0}",
    "templateSplitMissingTemplatesXml": "[SKIP] templates.xml nicht gefunden - Template-Aufteilung wird uebersprungen",
    "templateSplitNoTemplateNodes": "[SKIP] Keine Template-Knoten in templates.xml",
    "okWithMessage": "[OK] {0}",
    "creatingOutputDirectory": "[INFO] Ausgabeverzeichnis wird erstellt: {0}",
    "outputDirectoryCreated": "[OK] Ausgabeverzeichnis erfolgreich erstellt",
    "outputDirectoryCreateFailed": "[FEHLER] Ausgabeverzeichnis '{0}' konnte nicht erstellt werden: {1}",
    "clearedExistingOutputFolder": "[INFO] Vorhandenen Ausgabeordner geleert",
    "outputFolderClearFailed": "[FEHLER] Ausgabeordner konnte nicht geleert werden: {0}",
    "gameDirectoryNotFound": "Spielverzeichnis nicht gefunden: {0}",
    "solutionsLabel": "Loesungen:",
    "solutionVerifyGamePath": "  1. Anno-Spielinstallationspfad ueberpruefen",
    "solutionUseFullPath": "  2. Vollstaendigen Pfad zum Anno-Installationsverzeichnis verwenden",
    "solutionRunLauncher": "  3. Ueber Launcher-Skript ausfuehren fuer automatische Erkennung",
    "mergingInheritedProperties": "[FIX] Geerbte Eigenschaften von uebergeordneten Assets werden zusammengefuehrt",
    "guidIndexNull": "GuidIndex ist null - Abhaengigkeiten koennen nicht aufgeloest werden.",
    "dependenciesResolvedComplete": "[COMPLETE] \u2713 {0} Abhaengigkeiten aufgeloest",
    "formatFeatureVectorCleanup": "VectorElement-Bereinigung",
    "formatFeatureRegionalIngredients": ", Regionale Zutaten",
    "formatFeatureCommentsFolders": ", Kommentare (-c), Ordner (-t)",
    "formatFeatureComments": "Uebersetzte Kommentare (-c)",
    "formatFeatureFolders": "Template-Ordner (-t)",
    "formatFeatureFlaggedOnly": "nur markierte Nachbearbeitung",
    "formatProcessingFiles": "[FORMAT] {0} Dateien werden verarbeitet - {1}",
    "finalProcessingFiles": "Abschliessende Verarbeitung von {0} Dateien...",
    "applyingXmlCleanup": "Anwenden: XML-Bereinigung",
    "applyingRegionalIngredients": ", Regionale Zutaten",
    "applyingTranslations": ", Uebersetzungen",
    "applyingFolderOrganization": ", Ordnerorganisation",
    "finalProcessingCompleted": "[COMPLETE] Abschliessende Verarbeitung abgeschlossen:",
    "vectorCleanupApplied": "  * VectorElement-Bereinigung: Auf alle {0} Assets angewendet",
    "vectorCleanupSkippedSplitOnly": "  * VectorElement-Bereinigung: Uebersprungen (--no-default-properties / nur Aufteilung)",
    "translationCommentsSummary": "  * Uebersetzungskommentare: {0}",
    "templateOrganizationSummary": "  * Template-Organisation: {0}",
    "addedCFlag": "Hinzugefuegt (Flag -c)",
    "skippedNoCFlag": "Uebersprungen (kein Flag -c)",
    "appliedTFlag": "Angewendet (Flag -t)",
    "skippedNoTFlag": "Uebersprungen (kein Flag -t)",
    "processingAssetProgress": "Verarbeiten: {0}",
    "failedToLoadXmlFile": "[FEHLER] XML-Datei konnte nicht geladen werden: {0}",
    "unexpectedFileProcessingError": "[FEHLER] Unerwarteter Fehler bei der Dateiverarbeitung: {0}",
    "formatSingleFileFailed": "FormatSingleFile fehlgeschlagen fuer {0}: {1}",
    "couldNotMoveToTemplateFolder": "[WARN] Datei konnte nicht in Template-Ordner verschoben werden: {0}",
    "parentItemNull": "[WARN] Uebergeordnetes Element an Index {0} ist null",
    "propertyScanAnalyze": "[ANALYZE] properties.xml wird gescannt, um kommentarfaehige XML-Elemente zu identifizieren...",
    "propertyScanInfo": "[INFO] Eigenschaften mit Wert '0' werden gesucht, die uebersetzte GUID-Kommentare erhalten koennen",
    "propertyScanComplete": "[COMPLETE] Eigenschaftsanalyse: {0} XML-Elemente koennen uebersetzte Kommentare erhalten",
    "translationMappingsLoading": "[TRANS] GUID-Text-Uebersetzungszuordnungen werden geladen ({0})...",
    "translationDictionaryBuilding": "[INFO] Woerterbuch wird erstellt, um numerische GUIDs in lesbare Namen umzuwandeln",
    "translationFileLoadFailed": "[FEHLER] Uebersetzungsdatei '{0}' konnte nicht geladen werden: {1}",
    "translationDictionaryComplete": "[COMPLETE] Uebersetzungswoerterbuch: {0} GUID-zu-Name-Zuordnungen bereit",
    "filesFound": "{0} Dateien gefunden",
    "formatProcessingMainOutputFiles": "[FORMAT] {0} Haupt-Ausgabedateien werden verarbeitet",
    "formatProcessingBaseAssetGuidFilesNoMove": "[FORMAT] {0} BaseAssetGUID-Referenzdateien werden verarbeitet (kein Ordnerwechsel)",
    "assetExtractionSuccess": "[ERFOLG] \u2713 Asset-Extraktion erfolgreich abgeschlossen!",
    "mergeCheckingTemplateInheritance": "[MERGE] {0} Assets werden auf Template-Eigenschaftsvererbung geprueft...",
    "mergeOnlyFixlistTemplates": "[INFO] Nur Fixlist-Templates erhalten vollstaendig zusammengefuehrte Eigenschaften",
    "inheritingTemplateProperties": "Template-Eigenschaften werden fuer {0} Assets vererbt...",
    "mergingAssetProgress": "Zusammenfuehren: {0}",
    "mergeAssetFailed": "[FEHLER] {0} konnte nicht zusammengefuehrt werden: {1}",
    "templateInheritanceComplete": "[COMPLETE] Template-Vererbung: {0}/{1} Assets haben vollstaendige Eigenschaften erhalten",
    "templateNotFoundInCache": "[WARN] Template '{0}' nicht im Cache gefunden - das sollte nicht passieren",
    "templatesCheckingUpdate": "[TEMPLATES] Wird geprueft, ob Template-Konfiguration aktualisiert werden muss...",
    "rdaAnno117Detected": "[RDA] Anno 117 erkannt - assets.xml, templates.xml, properties.xml, properties-meta.xml, datasets.xml, audio_generated.xml werden entpackt...",
    "rdaExtractingAnno117CoreFiles": "[INFO] Kern-Spieldefinitionsdateien aus Anno 117 RDA-Archiven werden extrahiert",
    "rdaAnno1800Detected": "[RDA] Anno 1800 erkannt - assets.xml, templates.xml, properties-toolone.xml, datasets.xml werden entpackt...",
    "rdaExtractingAnno1800CoreFiles": "[INFO] Kern-Spieldefinitionsdateien aus Anno 1800 RDA-Archiven werden extrahiert",
    "rdaDecompressionSuccessful": "[COMPLETE] RDA-Entpackung erfolgreich - Spieldaten jetzt als XML zugaenglich",
    "loadingGameTemplatesConfig": "[CONFIG] Spiel-Templates und Verarbeitungskonfigurationen werden geladen...",
    "convertingRawXmlToMods": "[INFO] Roh-XML-Spieldaten werden in installierbare Anno-Mod-Dateien konvertiert",
    "configurationLoadedReady": "[READY] Konfiguration geladen - Asset-Konvertierung wird gestartet...",
    "rdaExtractionFailed": "[FEHLER] RDA-Extraktion fehlgeschlagen: {0}",
    "couldNotCopyToSourceXml": "[WARN] {0} konnte nicht nach source_xml kopiert werden: {1}",
    "rdaCompleteSelectLanguage": "[RDA COMPLETE] Spieldateien extrahiert - Sprache waehlen und erneut ausfuehren fuer Asset-Verarbeitung",
    "assetsXmlDocumentElementLoadFailed": "[FEHLER] assets.xml-Dokumentelement konnte nicht geladen werden",
    "singleGuidAsset": "[SINGLE GUID] Asset: {0} - {1}",
    "singleGuidXmlOutput": "[SINGLE GUID XML] Ausgabe: {0}",
    "rdaFilesContainAssets": "RDA-Dateien sind Container-Archive, die alle Anno-Spiel-Assets in komprimiertem Binaerformat speichern",
    "pipelineStarting": "Asset-Extraktionspipeline wird gestartet...",
    "phaseRdaAnno117": "\n=== PHASE 1: Extrahieren aus {0} Anno 117 RDA-Archiven ===",
    "phaseRdaAnno1800": "\n=== PHASE 1: Extrahieren aus {0} Anno 1800 RDA-Archiven ===",
    "rdaLongRunningNote": "Dies kann je nach Laufwerksgeschwindigkeit mehrere Minuten dauern...\n",
    "rdaExtractionCompleteNonDebug": "RDA-Extraktion abgeschlossen - {0}/{1} Archive verarbeitet in {2}",
    "rdaExtractionCompleteShort": "RDA-Extraktion abgeschlossen ({0}/{1} Archive in {2})",
    "phaseGuidIndex": "\n=== PHASE 2.5: GUID-Index wird aufgebaut ===",
    "guidIndexComplete": "GUID-Index erstellt in {0}",
    "extractedAssetsCount": "{0} Assets extrahiert.",
    "mergedTemplatesCount": "Geerbte Eigenschaften fuer {0} Assets zusammengefuehrt.",
    "dependencyResolutionComplete": "Abhaengigkeitsaufloesung abgeschlossen fuer {0} Assets in {1}",
    "translationsLoadedCount": "{0} Uebersetzungen geladen.",
    "assetNamesLoadedCount": "{0} Asset-Namen geladen.",
    "filesFormattedCount": "{0} Dateien formatiert.",
    "extractionCompleteHeader": "\n=== EXTRAKTION ABGESCHLOSSEN ===",
    "processedAssetsSummary": "{0} Assets verarbeitet.",
    "assetModsCreatedNote": "Asset-Mod-Ordner erstellt.",
    "totalTimeSummary": "Gesamtzeit: {0}",
    "issueSummarySampleGuid": "GUID {0} \u2014 {1}",
    "issueSummarySampleBulletPrefix": "  \u2022 ",
    "issueSummarySampleFileDetail": "{0} \u2014 {1}",
    # debug strings
    "debugWorkPlanAnnounced": "[DEBUG][PLAN] Arbeitseinheiten-Budget fuer UI-Fortschritt: {0} (XML-Hauptdateien: {1}; inkl. GUID-Index {2}, Merge {3}, Abhaengigkeiten {4}, Formatierung {5}, Asset-Mods {6})",
    "debugTemplateMergeStats": "[DEBUG][MERGE] Template-Vererbung: {0} aus Fixlist zusammengefuehrt, {1} einfach beibehalten (nicht in Fixlist)",
    "debugParentCacheStats": "[DEBUG][CACHE] Eltern-GUID-Cache: {0} von Disk geladen, {1} aus Cache wiederverwendet",
    "debugFormattingFileStats": "[DEBUG][FORMAT] Dateiarbeit: {0} annotiert ({1} Kommentare), {2} in Template-Ordner verschoben, {3} ohne Template-Knoten",
    "debugModPackageStats": "[DEBUG][MODS] {0} Mod-Pakete erstellt ({1} uebersprungen)",
    "debugPhaseGuidIndex": "[DEBUG][PHASE] GUID-Dateiindex aufbauen (ordnet jede Asset-GUID ihrem XML-Pfad fuer Merge/Abhaengigkeitsaufloesung zu)",
    "debugGuidIndexComplete": "[DEBUG][PHASE] GUID-Index bereit in {0} - {1} Dateien indiziert",
    "debugTemplateSplitFile": "[DEBUG][SPLIT] Template-Datei geschrieben: {0}.xml",
    "debugTemplateSplitSummary": "[DEBUG][SPLIT] {0} Templates aus {1} in {2} aufgeteilt (nur erste {3} Dateinamen protokolliert)",
    "debugAssetModsProcessingFiles": "[DEBUG] Dateien in Asset-Mod-Pakete werden verarbeitet: {0}",
    "debugAssetModsCreatingPackage": "[DEBUG] Mod-Paket wird erstellt fuer: {0}",
    "debugAssetModsSkippedInvalidMetadata": "[DEBUG] {0} uebersprungen - ungueltige oder fehlende Metadaten",
    "debugAssetModsPackageCreated": "[DEBUG] Mod-Paket erstellt: {0} -> GUID {1} ({2})",
    "debugTotalArguments": "[DEBUG] Gesamtargumente: {0}",
    "debugFlagsApplied": "[DEBUG] Angewendete Flags: -c(Kommentare)={0} -f(BaseAssetGUID)={1} -t(Template-Ordner)={2} --modops-wrap={3} --split-templates={4} --create-asset-mods={5}",
    "debugSingleGuidFilter": "[DEBUG] singleGuidFilter='{0}', Laenge={1}",
    "debugRegistryIncludesAssets": "[DEBUG] Registrierung umfasst alle Gebaeude, Produkte, Gegenstaende und Spielobjekte",
    "debugPropertiesWillGetComments": "[DEBUG] Diese Eigenschaften erhalten <!-- Kommentare --> bei Verwendung von Flag -c",
    "debugTranslationExamples": "[DEBUG] Beispiele: GUID '1010017' -> 'Coins', '1010196' -> 'Timber'",
    "debugStep3AddingComments": "[DEBUG] SCHRITT 3: Uebersetzte Kommentare werden XML-Elementen hinzugefuegt (Flag -c aktiviert)",
    "debugStep3SkippingComments": "[DEBUG] SCHRITT 3: Kommentare werden uebersprungen - Flag -c verwenden, um uebersetzte Kommentare zu aktivieren",
    "debugStep4OrganizingFolders": "[DEBUG] SCHRITT 4: Dateien werden in Template-Ordner organisiert (Flag -t aktiviert)",
    "debugStep4KeepingMainDirectory": "[DEBUG] SCHRITT 4: Dateien bleiben im Hauptverzeichnis - Flag -t fuer Template-Ordner verwenden",
    "debugXmlLoadError": "[DEBUG] XML-Ladefehler: {0}",
    "debugVectorElementsRemoved": "[DEBUG] VectorElement-Knoten aus XML-Struktur entfernt: {0}",
    "debugNoTemplateNodeFound": "[DEBUG] Kein Template-Knoten in {0} gefunden - wird fortgesetzt",
    "debugTranslatedCommentsAdded": "[DEBUG] Uebersetzte Kommentare zu XML-Elementen hinzugefuegt: {0}",
    "debugBuildingRegionDetected": "[DEBUG] Gebaeude-Region erkannt: {0} ({1})",
    "debugAppliedIngredients": "[DEBUG] {1} Zutaten auf Gebaeude-Kosten angewendet: {0}",
    "debugStep4MovingFileToTemplateFolder": "[DEBUG] SCHRITT 4: Datei wird in Template-Ordner '{0}' verschoben (Flag -t aktiviert)",
    "debugTemplateSkippedNotInFixlist": "[DEBUG] UEBERSPRUNGEN: Template '{0}' nicht in Fixlist - Basis-Asset bleibt",
    "debugTemplateMergingInFixlist": "[DEBUG] ZUSAMMENFUEHREN: Template '{0}' ist in Fixlist - vollstaendige Eigenschaften werden vererbt",
    "debugCacheBuildingTemplateProperties": "[CACHE] Template-Eigenschafts-Cache wird erstellt fuer Templates: {0}...",
    "debugCacheTemplateFailed": "[WARN] Template '{0}' konnte nicht gecacht werden: {1}",
    "debugCacheTemplatePropertiesComplete": "[CACHE] Template-Eigenschaftsbaeume gecacht: {0} (spart ~{1} ms bei XPath-Suchen)",
    "debugDependencyCacheInitialized": "[FIX] Abhaengigkeits-Aufloesung-Caches initialisiert - bereit fuer Phase 5 (Eintraege im GUID-Index: {0})",
    "debugParentAssetLoadedFromCache": "[CACHE] Eltern-Asset {0} aus Cache geladen (Treffer)",
    "debugParentAssetNotFound": "[WARN] Eltern-Asset {0} nicht gefunden",
    "debugParentAssetLoadedFromDisk": "[CACHE] Eltern-Asset {0} von Disk geladen und gecacht",
    "debugParentAssetLoadFailed": "[FEHLER] Eltern-Asset {0} konnte nicht geladen werden: {1}",
    "debugDependencyCacheCleared": "[COMPLETE] Abhaengigkeits-Aufloesung-Caches geleert - Speicher freigegeben",
    "debugArgumentValue": "[DEBUG] args[{0}] = '{1}'",
    "debugStartupFromGui": "[DEBUG][START] game='{0}' | output='{1}' | assetTexts={2} | consoleLang={3} | flags: {4}",
    "debugFlowStep": "[DEBUG][FLOW] {0}",
    "debugExtractedGuid": "[DEBUG] Extrahierte GUID: '{0}'",
    "debugCleanSingleGuidOutputFailed": "[DEBUG] Leeren des Single-GUID-Ausgabeordners fehlgeschlagen: {0}",
    "debugReadAssetNameFromOutputFailed": "[DEBUG] Asset-Name aus Ausgabe konnte nicht gelesen werden: {0}",
    "debugSingleGuidModeActive": "[DEBUG] SINGLE-GUID-MODUS AKTIV",
    "debugParseAssetFailed": "[DEBUG] Asset konnte nicht geparst werden: {0}",
    "debugInheritedIndexProcessingError": "[DEBUG] Fehler bei Verarbeitung von InheritedIndex: {0}",
    "debugElementTranslation": "[DEBUG] Element: <{0}>{1}</{0}> -> Uebersetzung: '{2}' (Laenge={3})",
    "debugInvalidCommentText": "[DEBUG] Ungueltiger Kommentartext: '{0}' - {1}",
    "debugCommentInsertionError": "[DEBUG] Fehler beim Einsetzen von Kommentar: {0} - {1}",
    "debugAnnotateFileCommentsError": "[DEBUG] Fehler in AnnotateFilesWithGuidComments bei {0}: {1}",
    "debugModExportSource": "[DEBUG][MODS] Quell-XML-Ordner: {0}",
    "debugModExportTarget": "[DEBUG][MODS] Mod-Pakete Ausgabe: {0}",
    "debugPhase7AddingComments": "[DEBUG] Phase 7: Uebersetzte GUID-Kommentare werden hinzugefuegt (Flag -c aktiviert)",
    "debugPhase7SkippingComments": "[DEBUG] Phase 7: Uebersetzte Kommentare werden uebersprungen (Flag -c deaktiviert)",
    "debugParentAssetRelocated": "[CACHE] Eltern-Asset {0} gefunden unter verschobenem Pfad: {1}",
    "debugFlowSplitOnlyComplete": "Schritte 4-7: uebersprungen (nur Aufteilung - reines assets.xml-Split abgeschlossen)",
    "debugFlowPhase4Skipped": "Schritt 4: uebersprungen (GUID-Index nicht benoetigt ohne -c oder -f)",
    "debugFlowPhase5Skipped": "Schritt 5: uebersprungen (--no-default-properties / Template-Merge deaktiviert)",
    "debugFlowPhase7Skipped": "Schritt 7: uebersprungen (kein -c, -t, Anreicherung oder Mod-Pakete)",
    "debugRdaArchiveInternals": "[DEBUG][RDA] Archiv-Interna: format={0}, parsedBlocks={1}, totalEntries={2}, entryFlags(compressed={3}, encrypted={4}, memory-resident={5}, deleted={6})",
    "debugRdaArchiveLayout": "[DEBUG][RDA] Archiv-Layout: fileBytes={0}, firstBlockOffset={1}, parsedBlockHeaders={2}",
    "debugRdaEntryFlagScope": "[DEBUG][RDA] Hinweis: entryFlags sind Flags pro Datei aus Block-Metadaten (keine Aussage, ob die gesamte .rda-Datei komprimiert ist oder nicht).",
    "debugRdaBlockDetail": "[DEBUG][RDA]   Block #{0}: offset={1}, flags={2} [compressed={3}, encrypted={4}, memory-resident={5}, deleted={6}], files={7}, dirSize={8}, dirSizeDecoded={9}, nextBlock={10}",
    "debugRdaBlockDetailSummary": "[DEBUG][RDA] Block-Header: {0} geparst, {1} mit Dateien (erste {2} dateitragende Bloecke werden angezeigt)",
    "debugRdaBlockDetailTruncated": "[DEBUG][RDA]   ... {0} weitere dateitragende Block(s) im Log weggelassen",
    "debugRdaNoFileBearingBlocks": "[DEBUG][RDA] Keine dateitragenden Bloecke im Archiv (leeres oder nur-Tombstone-Layout)",
    "debugRdaOutputInventory": "[DEBUG][RDA] Ausgabeordner hat jetzt {0} Datei(en) in {1}:",
    "debugRdaOutputFile": "[DEBUG][RDA]   \u2022 {0} ({1} Bytes)",
    "debugRdaOutputMissing": "[DEBUG][RDA] Ausgabeordner existiert nicht nach Extraktion: {0}",
    "debugRdaStartingPhase": "[DEBUG][RDA] RDA-Extraktionsphase {0} wird gestartet. Archive gefunden: {1}.",
    "debugRdaSkippingMissing": "[DEBUG][RDA] Fehlendes Archiv wird uebersprungen: {0}",
    "debugRdaProcessing": "[DEBUG][RDA] Verarbeite {0} ({1}/{2})",
    "debugRdaFoundCoreFiles": "[DEBUG][RDA] Alle benoetigten Dateien gefunden nach {0}. Stopp.",
    "debugRdaFinishedPhase": "[DEBUG][RDA] RDA-Extraktionsphase {0} abgeschlossen.",
    "debugGuidStartingBuild": "[DEBUG][GUID] GUID-Index-Aufbau wird gestartet. Dateien gesamt: {0}",
    "debugGuidFinishedIndexing": "[DEBUG][GUID] Indizierung abgeschlossen. Indiziert: {0}, Uebersprungen: {1}, Gesamt: {2}",
    "debugDepStartingResolution": "[DEBUG][DEP] Abhaengigkeitsaufloesung wird gestartet fuer {0} Dateien.",
    "debugDepNoBaseAssetGuid": "[DEBUG][DEP] BaseAssetGUID nicht gefunden in {0}.",
    "debugDepResolving": "[DEBUG][DEP] Aufloesen {0} (GUID: {1})",
    "debugDepSuccessfullyMerged": "[DEBUG][DEP] Eltern erfolgreich zusammengefuehrt in {0}",
    "debugDepCouldNotLoadParent": "[DEBUG][DEP] Eltern-Dokument fuer GUID {0} konnte nicht geladen werden: {1}",
    "debugDepComplete": "[DEBUG][DEP] Abhaengigkeitsaufloesung abgeschlossen. Verarbeitete Dateien: {0}.",
    "debugMergeBuiltXpaths": "[DEBUG][MERGE] {0} Ziel-XPaths fuer Merge in {1} erstellt",
    "debugMergeIdentifiedParentPaths": "[DEBUG][MERGE] {0} eindeutige Eltern-Pfade identifiziert.",
    "debugMergeFailedSelectPath": "[DEBUG][MERGE] Eltern-Pfad '{0}' konnte nicht ausgewaehlt werden: {1}",
    "debugMergeCompleted": "[DEBUG][MERGE] Merge abgeschlossen: {0} Knoten fuer {1}",
    "debugGuidScanRoot": "[DEBUG][GUID] XML wird gescannt unter: {0}",
    "debugGuidIndexedFile": "[DEBUG][GUID] GUID {0} indiziert -> {1}",
    "debugGuidDuplicateSkipped": "[DEBUG][GUID] Doppelte GUID {0} (ersten Pfad behalten, {1} uebersprungen)",
    "debugGuidSkippedFile": "[DEBUG][GUID] {0} uebersprungen \u2014 {1}",
    "debugExtractWroteFile": "[DEBUG][EXTRACT] Geschrieben {0} - {1} ({2}) -> {3} [{4}]",
    "debugTransSourceFile": "[DEBUG][TRANS] Uebersetzungsdatei wird geladen: {0}",
    "debugTransKeyMode": "[DEBUG][TRANS] Texttasten-Modus: {0} (LineId fuer Anno 117, GUID fuer Anno 1800)",
    "debugAssetRegistrySource": "[DEBUG][ASSETS] Asset-Registrierung wird geladen aus: {0}",
    "debugAssetRegistryPendingInheritance": "[DEBUG][ASSETS] Assets warten auf Eltern-Namensvererbung: {0}",
    "debugAssetInheritedName": "[DEBUG][ASSETS] Geerbter Name: Kind {0} <- Eltern {1} => '{2}'",
    "debugAssetInheritPending": "[DEBUG][ASSETS] Ausstehend (Eltern-Name noch nicht bereit): Kind {0} <- Eltern {1}",
    "debugAssetInheritSkipped": "[DEBUG][ASSETS] Vererbung uebersprungen: Kind {0} \u2014 {1}",
    "debugPropertyScanWhitelist": "[DEBUG][ANALYZE] Whitelist-Eigenschaften zusammengefuehrt: {0}",
    "debugPropertyEligible": "[DEBUG][ANALYZE] Kommentarfaehige Eigenschaft: {0}",
    "debugOutputLayoutAnnoAssets": "[DEBUG][PATHS] AnnoAssets-Wurzel: {0}",
    "debugOutputLayoutGameRoot": "[DEBUG][PATHS] Spiel-Ausgabe-Wurzel: {0}",
    "debugOutputLayoutAssetOut": "[DEBUG][PATHS] Asset-XML-Ausgabe: {0}",
    "debugOutputLayoutModOut": "[DEBUG][PATHS] Asset-Mod-Ausgabe: {0}",
    "debugOutputLayoutSingleMod": "[DEBUG][PATHS] Single-GUID-Mod-Ausgabe: {0}",
    "debugPhase2SourceXml": "[DEBUG][PHASE] Quell-XML-Ordner: {0}",
    "debugTemplateListPath": "[DEBUG][TEMPLATES] Template-Listen-Konfiguration: {0}",
    "debugTemplateFixlistCount": "[DEBUG][TEMPLATES] Fixlist-Templates (volle Vererbung): {0}",
    "debugMergeProcessingFile": "[DEBUG][MERGE] Datei wird verarbeitet: {0} (Template: {1})",
    "debugFormatProcessingFile": "[DEBUG][FORMAT] Datei wird verarbeitet: {0}",
    "debugFormatScanRoot": "[DEBUG][FORMAT] Ausgabeordner wird gescannt: {0}",
    "debugFormatNoTemplateNode": "[DEBUG][FORMAT] Kein Template-Knoten in {0} (wird fortgesetzt)",
    "debugAudioRegistrySource": "[DEBUG][ASSETS] Audio-Namen werden geladen aus: {0}",
    "debugDepRemovedEmptyStagingFolder": "[DEBUG][DEP] Leerer Staging-Ordner entfernt: {0}",
    "debugGuidIndexRefreshedAfterDeps": "[DEBUG][GUID] Index nach Abhaengigkeits-Merge aktualisiert: {0} Eintraege",
    "debugDepStagingFileDeleteFailed": "[DEBUG][DEP] Zusammengefuehrte Staging-Datei {0} konnte nicht geloescht werden: {1}",
    "debugDepStagingFolderDeleteFailed": "[DEBUG][DEP] Leerer Staging-Ordner {0} konnte nicht entfernt werden: {1}",
    "debugRdaAnno1800NoEarlyStop": "alle Archive gescannt (kein fruehzeitiger Stopp)",
    "debugRdaAnno1800PhaseSummary": "[DEBUG][RDA] Anno 1800 Phasen-Zusammenfassung: {0}/{1} Archive gescannt in {2}; {3}; {4} Einzeldatei(en) geschrieben",
    "debugRdaAnno1800SkipExistingPolicy": "[DEBUG][RDA] Anno 1800 Merge-Richtlinie: Einzeldatei-Ausgabe ueberspringen wenn Datei bereits existiert (aeltere Archive koennen neuere Patch-Dateien nicht ueberschreiben)",
    "debugRdaAnno1800StoppedAt": "fruehzeitiger Stopp bei {0}",
    "debugRdaArchiveCompact": "[DEBUG][RDA] {0}: {1} Bytes auf Disk, {2} Eintraege gescannt, 0 geschrieben ({3} auf Disk uebersprungen, {4} Filter-Miss)",
    "debugRdaArchiveExtractedSummary": "[DEBUG][RDA] {0}: {1} Bytes auf Disk, {2} Eintraege gescannt, {3} geschrieben ({4} auf Disk uebersprungen, {5} Pruefsumme/Metadaten)",
    "debugRdaArchivePath": "[DEBUG][RDA] Archiv wird geoeffnet: {0}",
    "debugRdaArchiveReadFailed": "[WARN] RDA-Archiv '{0}' konnte nicht gelesen werden: {1} - naechstes Archiv wird versucht",
    "debugRdaArchiveSearchOrder": "[DEBUG][RDA] Archiv-Suchreihenfolge: {0}",
    "debugRdaArchiveSearchOrderAnno1800": "[DEBUG][RDA] Archiv-Suchreihenfolge: data*.rda hoechster Index zuerst (Stopp wenn Kern-Dateien + Sprache gefunden)",
    "debugRdaArchiveSearchOrderAnno1800NewestWins": "[DEBUG][RDA] Archiv-Suchreihenfolge: data*.rda hoechster Index zuerst; erster Schreibvorgang gewinnt pro Einzeldateiname (neuester Patch beibehalten, kein Ueberschreiben aus aelteren Archiven)",
    "debugRdaArchiveSummary": "[DEBUG][RDA] Archiv '{0}': {1} Eintraege gescannt, {2} extrahiert, {3} Pruefsumme/Metadaten uebersprungen, {4} ungueltiger Pfad uebersprungen, {5} kein Filter-Treffer",
    "debugRdaAssetLanguage": "[DEBUG][RDA] Sprachanforderung fuer diesen Lauf: {0}",
    "debugRdaBareExtractMode": "[DEBUG][RDA] Extraktionsmodus: bare={0} (Dateien flach in Ausgabeordner nach Dateiname geschrieben)",
    "debugRdaContinueSearch": "[DEBUG][RDA] Kern-Dateien noch fehlend nach {0} - naechstes Archiv wird versucht",
    "debugRdaEarlyStopReason": "[DEBUG][RDA] Fruehzeitiger Stopp - alle benoetigten Dateien vorhanden: {0}",
    "debugRdaEarlyStopRequirements": "[DEBUG][RDA] Fruehzeitiger Stopp wenn alle vorhanden: {0}",
    "debugRdaFileProvenanceHeader": "[DEBUG][RDA] Einzeldatei-Herkunft (erster Schreibvorgang gewinnt - Quell-Archiv fuer jede Ausgabedatei):",
    "debugRdaFileProvenanceLine": "[DEBUG][RDA]   {0} <- {1} ({2} Bytes)",
    "debugRdaFilterCriteria": "[DEBUG][RDA] Filterkriterien ({0} ODER-Gruppen): {1}",
    "debugRdaFilterGroup": "[DEBUG][RDA]   Gruppe {0}: Treffer wenn {1}",
    "debugRdaGameRoot": "[DEBUG][RDA] Spielinstallations-Wurzel: {0}",
    "debugRdaMainDataFolder": "[DEBUG][RDA] Maindata-Ordner wird durchsucht: {0}",
    "debugRdaMissingArchive": "[DEBUG][RDA] Archiv nicht gefunden (uebersprungen): {0}",
    "debugRdaOutputFolder": "[DEBUG][RDA] Ausgabeordner (Extraktionsziel): {0}",
    "debugRdaProcessingOrder": "[DEBUG][RDA] Verarbeitungsreihenfolge in diesem Lauf: {0}",
    "debugRdaProcessingOrderCompact": "[DEBUG][RDA] Verarbeitungsreihenfolge: {0} -> {1} ({2} Archive, hoechster Patch-Index zuerst)",
    "debugRdaSkippedEntry": "[DEBUG][RDA] Uebersprungen: {0} \u2014 {1}",
}

applied = 0
for k, v in tr.items():
    if k in data and data[k] != v:
        data[k] = v
        applied += 1

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Applied {applied} translations to console_de.json")

# Verify
import json as j2
j2.loads(open(path, encoding='utf-8').read())
print("JSON valid: OK")
