#!/usr/bin/env python3
"""One-shot UI string translations for keys still identical to English. Run after editing Strings.json."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STRINGS_DIR = ROOT / "Localization" / "Languages"

LANGS = ("de", "fr", "es", "it", "pl", "ru", "zh", "ja", "ko", "tw")

# Flat key -> per-language value
TRANSLATIONS: dict[str, dict[str, str]] = {
    "labels.debugBadge": {
        "de": "DEBUG", "fr": "DEBUG", "es": "DEBUG", "it": "DEBUG", "pl": "DEBUG",
        "ru": "ОТЛАДКА", "zh": "调试", "ja": "デバッグ", "ko": "디버그", "tw": "偵錯",
    },
    "tooltips.overallPipelineProgress": {
        "de": "Gesamtfortschritt der Pipeline",
        "fr": "Progression globale du pipeline",
        "es": "Progreso general del proceso",
        "it": "Avanzamento complessivo della pipeline",
        "pl": "Ogólny postęp potoku",
        "ru": "Общий прогресс конвейера",
        "zh": "整体流程进度",
        "ja": "パイプライン全体の進捗",
        "ko": "전체 파이프라인 진행률",
        "tw": "整體流程進度",
    },
    "themes.Auto": {
        "de": "Automatisch", "fr": "Auto", "es": "Automático", "it": "Automatico", "pl": "Automatyczny",
        "ru": "Авто", "zh": "自动", "ja": "自動", "ko": "자동", "tw": "自動",
    },
    "statusMessages.singleGuidNumericOnly": {
        "de": "Einzel-GUID muss nur numerisch sein, z. B. 1010017.",
        "fr": "Le GUID unique doit être numérique uniquement, par ex. 1010017.",
        "es": "El GUID único debe ser solo numérico, p. ej. 1010017.",
        "it": "Il GUID singolo deve essere solo numerico, es. 1010017.",
        "pl": "Pojedynczy GUID musi być wyłącznie numeryczny, np. 1010017.",
        "ru": "Одиночный GUID должен содержать только цифры, например 1010017.",
        "zh": "单个 GUID 只能为数字，例如 1010017。",
        "ja": "単一 GUID は数字のみです（例: 1010017）。",
        "ko": "단일 GUID는 숫자만 가능합니다(예: 1010017).",
        "tw": "單一 GUID 只能為數字，例如 1010017。",
    },
    "statusMessages.singleGuidSourceXmlMissing": {
        "de": "Zuerst Spielextraktion ausführen, um source assets.xml zu erstellen.",
        "fr": "Exécutez d'abord l'extraction des fichiers du jeu pour créer source assets.xml.",
        "es": "Ejecute primero la extracción del juego para crear source assets.xml.",
        "it": "Esegui prima l'estrazione dei file di gioco per creare source assets.xml.",
        "pl": "Najpierw uruchom ekstrakcję plików gry, aby utworzyć source assets.xml.",
        "ru": "Сначала выполните извлечение файлов игры, чтобы создать source assets.xml.",
        "zh": "请先运行游戏文件提取以创建 source assets.xml。",
        "ja": "先にゲームファイルの抽出を実行して source assets.xml を作成してください。",
        "ko": "먼저 게임 파일 추출을 실행하여 source assets.xml을 생성하세요.",
        "tw": "請先執行遊戲檔案擷取以建立 source assets.xml。",
    },
    "statusMessages.singleGuidFound": {
        "de": "GUID {0} gefunden: {1}",
        "fr": "GUID {0} trouvé : {1}",
        "es": "GUID {0} encontrado: {1}",
        "it": "GUID {0} trovato: {1}",
        "pl": "Znaleziono GUID {0}: {1}",
        "ru": "Найден GUID {0}: {1}",
        "zh": "找到 GUID {0}：{1}",
        "ja": "GUID {0} を検出: {1}",
        "ko": "GUID {0} 찾음: {1}",
        "tw": "找到 GUID {0}：{1}",
    },
    "statusMessages.singleGuidNotFound": {
        "de": "GUID {0} wurde in assets.xml nicht gefunden.",
        "fr": "GUID {0} introuvable dans assets.xml.",
        "es": "GUID {0} no se encontró en assets.xml.",
        "it": "GUID {0} non trovato in assets.xml.",
        "pl": "Nie znaleziono GUID {0} w assets.xml.",
        "ru": "GUID {0} не найден в assets.xml.",
        "zh": "在 assets.xml 中未找到 GUID {0}。",
        "ja": "assets.xml に GUID {0} が見つかりません。",
        "ko": "assets.xml에서 GUID {0}을(를) 찾을 수 없습니다.",
        "tw": "在 assets.xml 中找不到 GUID {0}。",
    },
    "statusMessages.singleGuidLookupError": {
        "de": "assets.xml konnte für diese GUID nicht gelesen werden.",
        "fr": "Impossible de lire assets.xml pour ce GUID.",
        "es": "No se pudo leer assets.xml para este GUID.",
        "it": "Impossibile leggere assets.xml per questo GUID.",
        "pl": "Nie można odczytać assets.xml dla tego GUID.",
        "ru": "Не удалось прочитать assets.xml для этого GUID.",
        "zh": "无法扫描 assets.xml 以查找此 GUID。",
        "ja": "この GUID の assets.xml を読み取れませんでした。",
        "ko": "이 GUID에 대해 assets.xml을 읽을 수 없습니다.",
        "tw": "無法掃描 assets.xml 以查詢此 GUID。",
    },
    "statusMessages.singleGuidUnnamedAsset": {
        "de": "unbenanntes Asset",
        "fr": "asset sans nom",
        "es": "activo sin nombre",
        "it": "asset senza nome",
        "pl": "zasób bez nazwy",
        "ru": "ресурс без имени",
        "zh": "未命名资产",
        "ja": "名前のないアセット",
        "ko": "이름 없는 자산",
        "tw": "未命名資產",
    },
    "consoleMessages.consoleUiLanguage": {
        "de": "  UI / Konsolenmeldungen:",
        "fr": "  UI / messages console :",
        "es": "  UI / mensajes de consola:",
        "it": "  UI / messaggi console:",
        "pl": "  UI / komunikaty konsoli:",
        "ru": "  UI / сообщения консоли:",
        "zh": "  界面 / 控制台消息：",
        "ja": "  UI / コンソールメッセージ:",
        "ko": "  UI / 콘솔 메시지:",
        "tw": "  介面 / 主控台訊息：",
    },
    "consoleMessages.outputFolders": {
        "de": "Ausgabeordner:",
        "fr": "Dossiers de sortie :",
        "es": "Carpetas de salida:",
        "it": "Cartelle di output:",
        "pl": "Foldery wyjściowe:",
        "ru": "Выходные папки:",
        "zh": "输出文件夹：",
        "ja": "出力フォルダ:",
        "ko": "출력 폴더:",
        "tw": "輸出資料夾：",
    },
    "consoleMessages.outputXmlFolder": {
        "de": "  XML: {0}",
        "fr": "  XML : {0}",
        "es": "  XML: {0}",
        "it": "  XML: {0}",
        "pl": "  XML: {0}",
        "ru": "  XML: {0}",
        "zh": "  XML：{0}",
        "ja": "  XML: {0}",
        "ko": "  XML: {0}",
        "tw": "  XML：{0}",
    },
    "consoleMessages.outputModsFolder": {
        "de": "  Asset-Mods: {0}",
        "fr": "  Mods d'assets : {0}",
        "es": "  Mods de assets: {0}",
        "it": "  Mod asset: {0}",
        "pl": "  Mody zasobów: {0}",
        "ru": "  Моды ресурсов: {0}",
        "zh": "  资产模组：{0}",
        "ja": "  アセット Mod: {0}",
        "ko": "  에셋 모드: {0}",
        "tw": "  資產模組：{0}",
    },
    "consoleMessages.backendPhase3Label": {
        "de": "=== PHASE 3: ASSET-EXTRAKTION ===",
        "fr": "=== PHASE 3 : EXTRACTION D'ASSETS ===",
        "es": "=== FASE 3: EXTRACCIÓN DE ASSETS ===",
        "it": "=== FASE 3: ESTRAZIONE ASSET ===",
        "pl": "=== FAZA 3: EKSTRAKCJA ZASOBÓW ===",
        "ru": "=== ФАЗА 3: ИЗВЛЕЧЕНИЕ РЕСУРСОВ ===",
        "zh": "=== 阶段 3：资源提取 ===",
        "ja": "=== フェーズ 3: アセット抽出 ===",
        "ko": "=== 3단계: 에셋 추출 ===",
        "tw": "=== 階段 3：資產擷取 ===",
    },
    "consoleMessages.backendPhase3SplitLabel": {
        "de": "=== PHASE 3B: VORLAGEN AUFTEILEN ===",
        "fr": "=== PHASE 3B : DIVISION DES MODÈLES ===",
        "es": "=== FASE 3B: DIVIDIR PLANTILLAS ===",
        "it": "=== FASE 3B: SUDDIVISIONE TEMPLATE ===",
        "pl": "=== FAZA 3B: PODZIAŁ SZABLONÓW ===",
        "ru": "=== ФАЗА 3B: РАЗДЕЛЕНИЕ ШАБЛОНОВ ===",
        "zh": "=== 阶段 3B：拆分模板 ===",
        "ja": "=== フェーズ 3B: テンプレート分割 ===",
        "ko": "=== 3B단계: 템플릿 분할 ===",
        "tw": "=== 階段 3B：分割範本 ===",
    },
    "consoleMessages.backendPhase4GuidIndexLabel": {
        "de": "=== PHASE 4: GUID-DATEIINDEX ===",
        "fr": "=== PHASE 4 : INDEX FICHIERS GUID ===",
        "es": "=== FASE 4: ÍNDICE DE ARCHIVOS GUID ===",
        "it": "=== FASE 4: INDICE FILE GUID ===",
        "pl": "=== FAZA 4: INDEKS PLIKÓW GUID ===",
        "ru": "=== ФАЗА 4: ИНДЕКС ФАЙЛОВ GUID ===",
        "zh": "=== 阶段 4：GUID 文件索引 ===",
        "ja": "=== フェーズ 4: GUID ファイル索引 ===",
        "ko": "=== 4단계: GUID 파일 인덱스 ===",
        "tw": "=== 階段 4：GUID 檔案索引 ===",
    },
    "consoleMessages.backendPhase5MergeLabel": {
        "de": "=== PHASE 5: VORLAGENVERERBUNG (MERGE) ===",
        "fr": "=== PHASE 5 : HÉRITAGE DE MODÈLES (FUSION) ===",
        "es": "=== FASE 5: HERENCIA DE PLANTILLAS (FUSIÓN) ===",
        "it": "=== FASE 5: EREDITÀ TEMPLATE (MERGE) ===",
        "pl": "=== FAZA 5: DZIEDZICZENIE SZABLONÓW (SCALANIE) ===",
        "ru": "=== ФАЗА 5: НАСЛЕДОВАНИЕ ШАБЛОНОВ (СЛИЯНИЕ) ===",
        "zh": "=== 阶段 5：模板继承（合并）===",
        "ja": "=== フェーズ 5: テンプレート継承（マージ）===",
        "ko": "=== 5단계: 템플릿 상속(병합) ===",
        "tw": "=== 階段 5：範本繼承（合併）===",
    },
    "consoleMessages.backendPhase6DepsLabel": {
        "de": "=== PHASE 6: ABHÄNGIGKEITSAUFLÖSUNG ===",
        "fr": "=== PHASE 6 : RÉSOLUTION DES DÉPENDANCES ===",
        "es": "=== FASE 6: RESOLUCIÓN DE DEPENDENCIAS ===",
        "it": "=== FASE 6: RISOLUZIONE DIPENDENZE ===",
        "pl": "=== FAZA 6: ROZWIĄZYWANIE ZALEŻNOŚCI ===",
        "ru": "=== ФАЗА 6: РАЗРЕШЕНИЕ ЗАВИСИМОСТЕЙ ===",
        "zh": "=== 阶段 6：依赖解析 ===",
        "ja": "=== フェーズ 6: 依存関係の解決 ===",
        "ko": "=== 6단계: 종속성 해결 ===",
        "tw": "=== 階段 6：相依性解析 ===",
    },
    "consoleMessages.backendPhase7FormatLabel": {
        "de": "=== PHASE 7: FORMATIERUNG ===",
        "fr": "=== PHASE 7 : FORMATAGE ===",
        "es": "=== FASE 7: FORMATEO ===",
        "it": "=== FASE 7: FORMATTAZIONE ===",
        "pl": "=== FAZA 7: FORMATOWANIE ===",
        "ru": "=== ФАЗА 7: ФОРМАТИРОВАНИЕ ===",
        "zh": "=== 阶段 7：格式化 ===",
        "ja": "=== フェーズ 7: フォーマット ===",
        "ko": "=== 7단계: 서식 지정 ===",
        "tw": "=== 階段 7：格式化 ===",
    },
    "consoleMessages.backendPhase8ModsLabel": {
        "de": "=== PHASE 8: ASSET-MOD-PAKETE ===",
        "fr": "=== PHASE 8 : PAQUETS MOD D'ASSETS ===",
        "es": "=== FASE 8: PAQUETES MOD DE ASSETS ===",
        "it": "=== FASE 8: PACCHETTI MOD ASSET ===",
        "pl": "=== FAZA 8: PAKIETY MODÓW ZASOBÓW ===",
        "ru": "=== ФАЗА 8: ПАКЕТЫ МОДОВ РЕСУРСОВ ===",
        "zh": "=== 阶段 8：资源 Mod 包 ===",
        "ja": "=== フェーズ 8: アセット Mod パッケージ ===",
        "ko": "=== 8단계: 에셋 모드 패키지 ===",
        "tw": "=== 階段 8：資產模組套件 ===",
    },
    "consoleMessages.extractingFromRdaLabel": {
        "de": "Extrahiere aus RDA:",
        "fr": "Extraction depuis RDA :",
        "es": "Extrayendo desde RDA:",
        "it": "Estrazione da RDA:",
        "pl": "Ekstrakcja z RDA:",
        "ru": "Извлечение из RDA:",
        "zh": "从 RDA 提取：",
        "ja": "RDA から抽出:",
        "ko": "RDA에서 추출:",
        "tw": "從 RDA 擷取：",
    },
    "consoleMessages.indexingLabel": {
        "de": "Indiziere:",
        "fr": "Indexation :",
        "es": "Indexando:",
        "it": "Indicizzazione:",
        "pl": "Indeksowanie:",
        "ru": "Индексация:",
        "zh": "正在索引：",
        "ja": "索引作成:",
        "ko": "인덱싱:",
        "tw": "正在建立索引：",
    },
    "consoleMessages.inheritingLabel": {
        "de": "Übernehme Vererbung:",
        "fr": "Héritage :",
        "es": "Heredando:",
        "it": "Eredità:",
        "pl": "Dziedziczenie:",
        "ru": "Наследование:",
        "zh": "正在继承：",
        "ja": "継承:",
        "ko": "상속:",
        "tw": "正在繼承：",
    },
    "consoleMessages.annotatingLabel": {
        "de": "Annotiere:",
        "fr": "Annotation :",
        "es": "Anotando:",
        "it": "Annotazione:",
        "pl": "Adnotowanie:",
        "ru": "Аннотация:",
        "zh": "正在注释：",
        "ja": "注釈:",
        "ko": "주석:",
        "tw": "正在註解：",
    },
    "consoleMessages.creatingModLabel": {
        "de": "Erstelle Mod:",
        "fr": "Création du mod :",
        "es": "Creando mod:",
        "it": "Creazione mod:",
        "pl": "Tworzenie moda:",
        "ru": "Создание мода:",
        "zh": "正在创建模组：",
        "ja": "Mod 作成:",
        "ko": "모드 생성:",
        "tw": "正在建立模組：",
    },
    "consoleMessages.buildingGuidIndex": {
        "de": "GUID-Index wird erstellt",
        "fr": "Création de l'index GUID",
        "es": "Creando índice GUID",
        "it": "Creazione indice GUID",
        "pl": "Budowanie indeksu GUID",
        "ru": "Построение индекса GUID",
        "zh": "正在构建 GUID 索引",
        "ja": "GUID 索引を構築中",
        "ko": "GUID 인덱스 생성 중",
        "tw": "正在建立 GUID 索引",
    },
    "consoleMessages.annotatingTemplateComments": {
        "de": "Vorlagenkommentare werden annotiert",
        "fr": "Annotation des commentaires de modèles",
        "es": "Anotando comentarios de plantillas",
        "it": "Annotazione commenti template",
        "pl": "Adnotowanie komentarzy szablonów",
        "ru": "Аннотация комментариев шаблонов",
        "zh": "正在注释模板",
        "ja": "テンプレートコメントを注釈中",
        "ko": "템플릿 주석 추가 중",
        "tw": "正在註解範本註解",
    },
    "consoleMessages.creatingAssetMods": {
        "de": "Asset-Mods werden erstellt",
        "fr": "Création des mods d'assets",
        "es": "Creando mods de assets",
        "it": "Creazione mod asset",
        "pl": "Tworzenie modów zasobów",
        "ru": "Создание модов ресурсов",
        "zh": "正在创建资源模组",
        "ja": "アセット Mod を作成中",
        "ko": "에셋 모드 생성 중",
        "tw": "正在建立資產模組",
    },
    "issueSummary.groupHeader": {
        "de": "[{0}] {1}",
        "fr": "[{0}] {1}",
        "es": "[{0}] {1}",
        "it": "[{0}] {1}",
        "pl": "[{0}] {1}",
        "ru": "[{0}] {1}",
        "zh": "[{0}] {1}",
        "ja": "[{0}] {1}",
        "ko": "[{0}] {1}",
        "tw": "[{0}] {1}",
    },
    "issueSummary.sampleBullet": {
        "de": "  • ",
        "fr": "  • ",
        "es": "  • ",
        "it": "  • ",
        "pl": "  • ",
        "ru": "  • ",
        "zh": "  • ",
        "ja": "  • ",
        "ko": "  • ",
        "tw": "  • ",
    },
    "issueSummary.sampleGuid": {
        "de": "GUID {0} — {1}",
        "fr": "GUID {0} — {1}",
        "es": "GUID {0} — {1}",
        "it": "GUID {0} — {1}",
        "pl": "GUID {0} — {1}",
        "ru": "GUID {0} — {1}",
        "zh": "GUID {0} — {1}",
        "ja": "GUID {0} — {1}",
        "ko": "GUID {0} — {1}",
        "tw": "GUID {0} — {1}",
    },
    "issueSummary.sampleFileDetail": {
        "de": "{0} — {1}",
        "fr": "{0} — {1}",
        "es": "{0} — {1}",
        "it": "{0} — {1}",
        "pl": "{0} — {1}",
        "ru": "{0} — {1}",
        "zh": "{0} — {1}",
        "ja": "{0} — {1}",
        "ko": "{0} — {1}",
        "tw": "{0} — {1}",
    },
}


def set_path(data: dict, path: str, value: str) -> None:
    parts = path.split(".")
    cur = data
    for part in parts[:-1]:
        cur = cur.setdefault(part, {})
    cur[parts[-1]] = value


def main() -> None:
    updated = 0
    for lang in LANGS:
        path = STRINGS_DIR / f"Strings.{lang}.json"
        data = json.loads(path.read_text(encoding="utf-8"))
        for key, per_lang in TRANSLATIONS.items():
            if lang in per_lang:
                set_path(data, key, per_lang[lang])
                updated += 1
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Applied {updated} translation values across {len(LANGS)} UI locale files.")


if __name__ == "__main__":
    main()
